// 8-Bit 8asterd -- a nine-voice MIDI chiptune synthesiser for three
// AY-3-8910 programmable sound generators driven by an Arduino Leonardo.
//
// Copyright (C) 2026 Greg Miller, The Key & Cable Company
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details. You should have received a copy of the GNU General
// Public License along with this program. If not, see
// <https://www.gnu.org/licenses/>.
//
// Derived from:
//   Arduino MIDI Chiptune Synthesizer by Ian Harvey (TheSpodShed)
//     https://www.instructables.com/Arduino-MIDI-Chiptune-Synthesizer/
//   Dual AY-3-8910 MIDI module by Doge Microsystems
//     https://dogemicrosystems.ca/wiki/Dual_AY-3-8910_MIDI_module
// The reduced BC1-grounded control scheme, the note table and the original
// voice-allocation approach come from that work.

/*
 * The bulk of this firmware comes from: https://dogemicrosystems.ca/wiki/Dual_AY-3-8910_MIDI_module
 * 
 * Firmware Version 2.2 for the 8-Bit 8asterd by Semiotic Sounds
 * 
 * Added:
 * Drum Polyphony
 * Slow attack evelopes on channels 3 and 4
 * Altered drum sounds (808 bass and clave)
 * Arduino Reset function on MIDI KillAll message
 * Better voice distribution methodology
 */

// resetFunc() removed: All Notes Off now calls softReset() instead of
// rebooting the MCU. See softReset() further down.

// Uncomment to enable 5-pin DIN serial midi
#define SERIALMIDI

// Uncomment to enable USB midi
#define USBMIDI

// Uncomment to enable debugging output over USB serial
#define DEBUG

#include <avr/io.h>
#include <string.h>
#include <stdlib.h>

#ifdef USBMIDI
#include "MIDIUSB.h"
#endif

// We borrow one struct from MIDIUSB for traditional serial midi, so define it if were not using USBMIDI
#ifndef MIDIUSB_h
typedef struct
{
  uint8_t header;
  uint8_t byte1;
  uint8_t byte2;
  uint8_t byte3;
} midiEventPacket_t;
#endif

#ifdef SERIALMIDI
#include <MIDI.h>
MIDI_CREATE_INSTANCE(HardwareSerial, Serial1, MIDI);//Serial1 on pro micro
#endif

typedef unsigned short int ushort;

typedef unsigned char note_t;
#define NOTE_OFF 0

typedef unsigned char midictrl_t;

// --- Fast direct-port I/O -------------------------------------------------
// KEEP THESE STRUCTS ABOVE EVERY FUNCTION DEFINITION IN THIS FILE. The
// Arduino .ino preprocessor auto-generates function prototypes and inserts
// them immediately before the first function definition; pinHigh()/pinLow()
// take a BusPin&, so if BusPin is declared after that point the generated
// prototype references an undeclared type and the build fails with
// "'BusPin' does not name a type".
//
// digitalWrite() costs ~50+ cycles on AVR (pin validation, PWM-timer
// disable check, interrupt mask save/restore). Every register write here
// needs 8 data-bit writes plus several BDIR/BC2 toggles, and this happens
// constantly on the voice/envelope hot path while MIDI also needs servicing.
// We resolve each pin to its AVR PORT register + bitmask once at startup
// (via the standard Arduino pin-mapping macros, so this stays portable if
// pins are reassigned) and then do a 1-2 instruction read-modify-write
// instead. This is roughly an order of magnitude faster per pin toggle.

struct BusPin {
  volatile uint8_t *port;
  uint8_t mask;
};

static BusPin dbusPins[8];

struct ChipCtl {
  BusPin bdir;
  BusPin bc2;
};

static ChipCtl chipCtl[3]; // 0 = chip A, 1 = chip B, 2 = chip C

// Voice/FX parameter structs live up here for the same reason as BusPin
// above: any top-level function taking one (applyDrumMods) gets an
// auto-generated prototype inserted before the first function definition.

struct FXParams {
  ushort noisefreq;
  ushort tonefreq;
  ushort envdecay;
  ushort freqdecay;
  ushort timer;
  ushort shape;
};

struct ToneParams {
  ushort attack;
  ushort decay;
  ushort sustain; // Values 0..32
  ushort rel;
};

// --- Parameter bank -------------------------------------------------------
// parameters.h is GENERATED by generate.py (indices, ranges, defaults, and a
// layout-version byte). The bank is a flat uint8_t array in index order --
// the same array the web panel edits over serial and that presets are made
// of. Edit generate.py, re-run it, reflash; never edit parameters.h by hand.
#include "parameters.h"
#include "temperaments.h"
#include <EEPROM.h>

static uint8_t params[NUM_PARAMS];

// MIDI CC control. Every parameter answers to a CC so the box can be driven
// from whatever controller someone already owns. Defaults are laid out from
// CC_BASE upward, in the 70-119 "sound controller / undefined" range, which
// avoids mod wheel, volume, sustain, the bank-select LSBs and the channel
// mode messages. Any of them can be re-learned to whatever a controller
// actually sends, and the map rides along in EEPROM with the parameters.
#define CC_BASE 70
#define CC_NONE 255
static uint8_t ccMap[NUM_PARAMS];
static uint8_t ccLearnTarget = CC_NONE;   // parameter awaiting the next CC

static void loadDefaultCcMap() {
  for (uint8_t i = 0; i < NUM_PARAMS; i++) {
    uint8_t cc = CC_BASE + i;
    ccMap[i] = (cc <= 119) ? cc : CC_NONE;   // past 119 there is no room left
  }
}

// AY envelope shapes that loop continuously (P_BUZZ_SHAPE is an index here):
static const uint8_t buzzShapes[4] PROGMEM = { 8, 10, 12, 14 };

static void loadDefaults() {
  for (uint8_t i = 0; i < NUM_PARAMS; i++) {
    params[i] = pgm_read_byte(&PARAM_DEFAULT[i]);
  }
}

static void setParam(uint8_t idx, int val) {
  if (idx >= NUM_PARAMS) return;
  int lo = pgm_read_byte(&PARAM_MIN[idx]);
  int hi = pgm_read_byte(&PARAM_MAX[idx]);
  if (val < lo) val = lo;
  if (val > hi) val = hi;
  params[idx] = (uint8_t)val;
}

// EEPROM layout: '8' 'B' <layout version> <param count> <params...>
// The layout version is derived from the parameter definition by
// generate.py, so a saved bank from an older definition is simply ignored.
static void saveParamsToEEPROM() {
  EEPROM.update(0, '8');
  EEPROM.update(1, 'B');
  EEPROM.update(2, PARAM_LAYOUT_VERSION);
  EEPROM.update(3, NUM_PARAMS);
  for (uint8_t i = 0; i < NUM_PARAMS; i++) {
    EEPROM.update(4 + i, params[i]);
    EEPROM.update(4 + NUM_PARAMS + i, ccMap[i]);
  }
}

static bool loadParamsFromEEPROM() {
  if (EEPROM.read(0) != '8' || EEPROM.read(1) != 'B' ||
      EEPROM.read(2) != PARAM_LAYOUT_VERSION || EEPROM.read(3) != NUM_PARAMS) {
    return false;
  }
  for (uint8_t i = 0; i < NUM_PARAMS; i++) {
    setParam(i, EEPROM.read(4 + i)); // clamp on the way in
    uint8_t cc = EEPROM.read(4 + NUM_PARAMS + i);
    ccMap[i] = (cc <= 119 || cc == CC_NONE) ? cc : CC_NONE;
  }
  return true;
}

// Pin driver ---------------------------------------------

// Pin numbers all fit in a byte; PROGMEM keeps the table out of RAM.
static const uint8_t dbus[8] PROGMEM = { 2, 3, 4, 5, 6, 7, 8, 10 };

static const ushort
  BC2_A = 14,
  BDIR_A = 16,
  BC2_B = A1,
  BDIR_B = A0,
  BC2_C = A3,
  BDIR_C = A2,
  nRESET = 15,
  clkOUT = 9;

static const ushort DIVISOR = 7; // Set for 1MHz clock


static void clockSetup() {
   // Timer 1 setup for Mega32U4 devices
   //
   // Use CTC mode: WGM13..0 = 0100
   // Toggle OC1A on Compare Match: COM1A1..0 = 01
   // Use ClkIO with no prescaling: CS12..0 = 001
   // Interrupts off: TIMSK0 = 0
   // OCR0A = interval value
   
   TCCR1A = (1 << COM1A0);
   TCCR1B = (1 << WGM12) | (1 << CS10);
   TCCR1C = 0;
   TIMSK1 = 0;
   OCR1AH = 0;
   OCR1AL = DIVISOR; // NB write high byte first
}


static inline void pinHigh(const BusPin &p) { *p.port |= p.mask; }
static inline void pinLow(const BusPin &p)  { *p.port &= ~p.mask; }

static void setData(unsigned char db) {
  unsigned char bit = 1;
  for (ushort i = 0; i < 8; i++) {
    if (db & bit) pinHigh(dbusPins[i]);
    else pinLow(dbusPins[i]);
    bit <<= 1;
  }
}

static void initBusPins() {
  for (uint8_t i = 0; i < 8; i++) {
    uint8_t pin = pgm_read_byte(&dbus[i]);
    dbusPins[i].port = portOutputRegister(digitalPinToPort(pin));
    dbusPins[i].mask = digitalPinToBitMask(pin);
  }

  const ushort bdirPins[3] = { BDIR_A, BDIR_B, BDIR_C };
  const ushort bc2Pins[3]  = { BC2_A,  BC2_B,  BC2_C  };

  for (uint8_t c = 0; c < 3; c++) {
    chipCtl[c].bdir.port = portOutputRegister(digitalPinToPort(bdirPins[c]));
    chipCtl[c].bdir.mask = digitalPinToBitMask(bdirPins[c]);
    chipCtl[c].bc2.port  = portOutputRegister(digitalPinToPort(bc2Pins[c]));
    chipCtl[c].bc2.mask  = digitalPinToBitMask(bc2Pins[c]);
  }
}

#ifdef AY_EMULATOR
// Emulator seam. The browser build runs this exact firmware, so register
// writes are handed to the emulated chips instead of being bit-banged onto
// real pins. Costs nothing on AVR: the macro is not defined there.
extern void emuWriteReg(uint8_t chip, unsigned char reg, unsigned char db);
#endif

static void writeReg(uint8_t chip, unsigned char reg, unsigned char db) {
#ifdef AY_EMULATOR
  emuWriteReg(chip, reg, db);
  return;
#endif
  // Same BC1-kept-low NACT/BAR/IAB/DWS sequencing as the original, just
  // routed through direct port writes instead of digitalWrite().
  //
  // ATOMIC: an interrupt landing between the address latch and the data
  // write would corrupt the transfer. Nothing writes registers from an ISR
  // today, but the cost is a few cycles and it keeps the bus safe if
  // anything ever does again.
  uint8_t sreg_save = SREG;
  cli();
  ChipCtl &c = chipCtl[chip];

  // Inactive (BDIR BC2 BC1 0 0 0)
  pinLow(c.bdir);
  pinLow(c.bc2);

  // Set register address
  setData(reg);

  // BAR (Latch) (BDIR BC2 BC1 1 0 0)
  pinHigh(c.bdir);

  // Inactive (BDIR BC2 BC1 0 0 0)
  pinLow(c.bdir);

  // Set register contents
  setData(db);

  // Write (BDIR BC2 BC1 1 1 0)
  pinHigh(c.bc2);
  pinHigh(c.bdir);

  // Inactive (BDIR BC2 BC1 0 0 0)
  pinLow(c.bc2);
  pinLow(c.bdir);

  SREG = sreg_save;
}

// AY-3-8910 driver ---------------------------------------

class PSGRegs {
public:
  enum {
    TONEALOW = 0,
    TONEAHIGH,
    TONEBLOW,
    TONEBHIGH,
    TONECLOW,
    TONECHIGH,
    NOISEGEN,
    MIXER,
    TONEAAMPL,
    TONEBAMPL,
    TONECAMPL,
    ENVLOW,
    ENVHIGH,
    ENVSHAPE,
    IOA,
    IOB
  };

  //MIXER
//   0 = A+B+C+Noise            [0]
// 248 = A+B+C                  [1]
// 199 = Noise only on A+B+C    [2]
// 254 = A Only                 [3]
// 253 = B only                 [4]
// 251 = C only                 [5]
// 252 = A+B                    [6]
// 249 = B+C                    [7]
// 246 = A+Noise                [8]
// 237 = B+Noise                [9]
// 219 = C+Noise                [10]
// 238 = A+Noise on B           [11]
// 221 = B+Noise on C           [12]
// 243 = C+Noise on A           [13]
// 247 = Noise only on A        [14]
// 239 = Noise only on B        [15]
// 223 = Noise only on C        [16]
  
  // Chip-indexed register storage: regs[0]=chip A, regs[1]=chip B, regs[2]=chip C.
  // The original had three full copies of these arrays (regs_A/B/C,
  // lastregs_A/B/C) plus three near-identical writeReg_A/B/C and three
  // near-identical update_A/B/C. Every voice channel 0..8 maps onto one of
  // the three chips via chip = ch % 3 and a sub-channel sub = ch / 3 (0,3,6
  // -> chip A; 1,4,7 -> chip B; 2,5,8 -> chip C, matching the original
  // mapping exactly). That collapses what used to be three copy-pasted
  // if/else-if chains per method into one formula, and incidentally fixes a
  // real bug in the original setPercOff(): its chip-A branch read
  // regs_C[MIXER] and its chip-C branch read regs_A[MIXER] instead of their
  // own chip's mixer register.
  unsigned char regs[3][16];
  unsigned char lastregs[3][16];

  void init() {
    for (uint8_t c = 0; c < 3; c++) {
      for (int i = 0; i < 16; i++) {
        regs[c][i] = lastregs[c][i] = 0xFF;
        writeReg(c, i, regs[c][i]);
      }
    }
  }

  void update(uint8_t chip) {
    unsigned char *r = regs[chip];
    unsigned char *lr = lastregs[chip];
    for (int i = 0; i < 16; i++) {
      if (r[i] != lr[i]) {
        writeReg(chip, i, r[i]);
        lr[i] = r[i];
      }
    }
  }

  void updateAll() {
    update(0);
    update(1);
    update(2);
  }

  void setTone(ushort ch, ushort divisor, ushort ampl) {
    uint8_t chip = ch % 3;
    uint8_t sub  = ch / 3;
    unsigned char *r = regs[chip];

    r[TONEALOW  + (sub<<1)] = (divisor & 0xFF);
    r[TONEAHIGH + (sub<<1)] = (divisor >> 8);
    r[TONEAAMPL + sub] = ampl;

    ushort mask = (8+1) << sub;
    r[MIXER] = (r[MIXER] | mask) ^ (1 << sub);
  }

  void setToneAndNoise(ushort ch, ushort divisor, ushort noisefreq, ushort ampl) {
    uint8_t chip = ch % 3;
    uint8_t sub  = ch / 3;
    unsigned char *r = regs[chip];

    r[TONEALOW  + (sub<<1)] = (divisor & 0xFF);
    r[TONEAHIGH + (sub<<1)] = (divisor >> 8);
    r[NOISEGEN] = noisefreq;
    r[TONEAAMPL + sub] = ampl;

    ushort mask = (8+1) << sub;
    ushort bits = (noisefreq < 16 ? 8 : 0) + (divisor > 0 ? 1 : 0);
    r[MIXER] = (r[MIXER] | mask) ^ (bits << sub);
  }

  // Pitch only, for a channel something else owns the amplitude of. Also
  // re-asserts tone and noise OFF in the CACHE every tick. Doing it with a
  // raw writeReg left the cache still saying "tone enabled", so any
  // invalidate() -- which every parameter change causes -- rewrote the
  // mixer from the cache and the square came back underneath.
  void setTonePitchOnly(ushort ch, ushort divisor) {
    uint8_t chip = ch % 3, sub = ch / 3;
    unsigned char *r = regs[chip];
    r[TONEALOW  + (sub << 1)] = divisor & 0xFF;
    r[TONEAHIGH + (sub << 1)] = (divisor >> 8) & 0x0F;
    r[MIXER] |= (uint8_t)((1u << sub) | (8u << sub));
  }

  void setEnvelope(ushort ch, ushort divisor, ushort shape) {
    uint8_t chip = ch % 3;
    unsigned char *r = regs[chip];
    r[ENVLOW]  = (divisor & 0xFF);
    r[ENVHIGH] = (divisor >> 8);
    r[ENVSHAPE] = shape;

    // Writing R13 is what RESTARTS the envelope, and the register cache
    // suppresses a write when the value has not changed. Every drum in the
    // kit uses shape 9, so a drum landing on a chip whose envelope is still
    // set to 9 by another drum got no restart at all -- it played into an
    // envelope that had already decayed to nothing, and was silent. Push the
    // period through the cache, then rewrite the shape unconditionally.
    update(chip);
    writeReg(chip, ENVSHAPE, (unsigned char)shape);
    lastregs[chip][ENVSHAPE] = (unsigned char)shape;
  }

  void setPercOff(ushort ch) {
    uint8_t chip = ch % 3;
    uint8_t sub  = ch / 3;
    unsigned char *r = regs[chip];

    ushort mask = (8+1) << sub;
    r[MIXER] |= mask;
    r[TONEAAMPL + sub] = 0;

    // The envelope generator is per-CHIP and shared by all three channels.
    // Zeroing it unconditionally cut off any other drum still sounding on
    // this chip, which is why drums choked each other. Only reset it once
    // no other channel here is still driven by it (M bit, 0x10).
    bool envInUse = false;
    for (uint8_t s2 = 0; s2 < 3; s2++) {
      if (s2 != sub && (r[TONEAAMPL + s2] & 0x10)) { envInUse = true; break; }
    }
    if (!envInUse && r[ENVSHAPE] != 0) {
      r[ENVSHAPE] = 0;
      update(chip); // Force flush
    }
  }

  // setOff() was an exact duplicate of setPercOff() in the original.
  void setOff(ushort ch) {
    setPercOff(ch);
  }

  // --- Buzzy bass -----------------------------------------------------
  // The AY's envelope generator is one-per-chip, shared by all three of
  // that chip's channels, and a channel's volume is driven by it whenever
  // bit 4 (0x10, the "M" bit) of its amplitude register is set -- in which
  // case the lower 4 (fixed-level) bits are ignored by the chip. ratio
  // scales the channel's tone divisor to get the envelope-period divisor;
  // there's no clean closed-form for "in tune", so this is meant to be
  // tuned by ear via the ratio control rather than computed exactly.
  void applyBuzz(uint8_t chip, uint8_t sub, ushort toneDivisor, uint8_t ratio,
                 uint8_t shape, int8_t detune) {
    unsigned char *r = regs[chip];
    // The envelope's full cycle is clock/(256*EP) while the tone is
    // clock/(16*TP), so the envelope only oscillates AT the note when
    // EP = TP/16. Multiplying the tone divisor directly, as this used to,
    // put it four octaves below the note -- a slow amplitude pulse rather
    // than a waveform. Divided down, the looping shapes become what they
    // actually are: a hardware sawtooth or triangle at the played pitch.
    // Ratio now means octaves below that: 1 unison, 2 an octave, 4 two.
    int32_t envDivisor = (((int32_t)toneDivisor * ratio) + 8) / 16 + detune;
    if (envDivisor < 1) envDivisor = 1;
    if (envDivisor > 65535) envDivisor = 65535;
    r[ENVLOW]  = envDivisor & 0xFF;
    r[ENVHIGH] = envDivisor >> 8;
    r[ENVSHAPE] = shape;
    r[TONEAAMPL + sub] = 0x10; // M=1: volume follows the envelope generator
  }

  // Forces the next update() to rewrite every register. Needed after the
  // Warp Zone writes straight to the chip behind the cache's back: without
  // this the cache still believes the hardware matches regs[] and would
  // never correct the glitched values.
  void invalidate() {
    for (uint8_t c = 0; c < 3; c++) {
      for (uint8_t i = 0; i < 16; i++) lastregs[c][i] = ~regs[c][i];
    }
  }

  void clearBuzz(uint8_t chip, uint8_t sub) {
    // Just drop the envelope-mode bit; the very next normal tone/amplitude
    // write for this voice (next 100Hz tick, at most 10ms away) restores
    // the correct fixed-level volume.
    regs[chip][TONEAAMPL + sub] &= ~0x10;
  }
};

static PSGRegs psg;

// Voice generation ---------------------------------------

static const ushort
  MIDI_MIN = 24,
  MIDI_MAX = 96,
  N_NOTES = (MIDI_MAX+1-MIDI_MIN);

static const ushort note_table[N_NOTES] PROGMEM = {
   1911, // MIDI 24, 32.70 Hz
   1804, // MIDI 25, 34.65 Hz
   1703, // MIDI 26, 36.71 Hz
   1607, // MIDI 27, 38.89 Hz
   1517, // MIDI 28, 41.20 Hz
   1432, // MIDI 29, 43.65 Hz
   1351, // MIDI 30, 46.25 Hz
   1276, // MIDI 31, 49.00 Hz
   1204, // MIDI 32, 51.91 Hz
   1136, // MIDI 33, 55.00 Hz
   1073, // MIDI 34, 58.27 Hz
   1012, // MIDI 35, 61.74 Hz
   956, // MIDI 36, 65.41 Hz
   902, // MIDI 37, 69.30 Hz
   851, // MIDI 38, 73.42 Hz
   804, // MIDI 39, 77.78 Hz
   758, // MIDI 40, 82.41 Hz
   716, // MIDI 41, 87.31 Hz
   676, // MIDI 42, 92.50 Hz
   638, // MIDI 43, 98.00 Hz
   602, // MIDI 44, 103.83 Hz
   568, // MIDI 45, 110.00 Hz
   536, // MIDI 46, 116.54 Hz
   506, // MIDI 47, 123.47 Hz
   478, // MIDI 48, 130.81 Hz
   451, // MIDI 49, 138.59 Hz
   426, // MIDI 50, 146.83 Hz
   402, // MIDI 51, 155.56 Hz
   379, // MIDI 52, 164.81 Hz
   358, // MIDI 53, 174.61 Hz
   338, // MIDI 54, 185.00 Hz
   319, // MIDI 55, 196.00 Hz
   301, // MIDI 56, 207.65 Hz
   284, // MIDI 57, 220.00 Hz
   268, // MIDI 58, 233.08 Hz
   253, // MIDI 59, 246.94 Hz
   239, // MIDI 60, 261.63 Hz
   225, // MIDI 61, 277.18 Hz
   213, // MIDI 62, 293.66 Hz
   201, // MIDI 63, 311.13 Hz
   190, // MIDI 64, 329.63 Hz
   179, // MIDI 65, 349.23 Hz
   169, // MIDI 66, 369.99 Hz
   159, // MIDI 67, 392.00 Hz
   150, // MIDI 68, 415.30 Hz
   142, // MIDI 69, 440.00 Hz
   134, // MIDI 70, 466.16 Hz
   127, // MIDI 71, 493.88 Hz
   119, // MIDI 72, 523.25 Hz
   113, // MIDI 73, 554.37 Hz
   106, // MIDI 74, 587.33 Hz
   100, // MIDI 75, 622.25 Hz
   95, // MIDI 76, 659.26 Hz
   89, // MIDI 77, 698.46 Hz
   84, // MIDI 78, 739.99 Hz
   80, // MIDI 79, 783.99 Hz
   75, // MIDI 80, 830.61 Hz
   71, // MIDI 81, 880.00 Hz
   67, // MIDI 82, 932.33 Hz
   63, // MIDI 83, 987.77 Hz
   60, // MIDI 84, 1046.50 Hz
   56, // MIDI 85, 1108.73 Hz
   53, // MIDI 86, 1174.66 Hz
   50, // MIDI 87, 1244.51 Hz
   47, // MIDI 88, 1318.51 Hz
   45, // MIDI 89, 1396.91 Hz
   42, // MIDI 90, 1479.98 Hz
   40, // MIDI 91, 1567.98 Hz
   38, // MIDI 92, 1661.22 Hz
   36, // MIDI 93, 1760.00 Hz
   34, // MIDI 94, 1864.66 Hz
   32, // MIDI 95, 1975.53 Hz
   30, // MIDI 96, 2093.00 Hz
};

static const ushort MAX_TONES = 4;
// Re-pointed when the envelope parameters became TIMES rather than per-tick
// rates, so these channels keep the shapes they had.
static const ToneParams tones[MAX_TONES] PROGMEM = {
  { 1, 26, 32, 19 },
  { 1, 26,  1, 19 },
  { 21, 32, 1, 19 },
  { 24, 32, 32, 32 }
};

// For glide: the divisor of the most recently started melodic note, so a
// new note can slide in from wherever the last one landed.
static ushort g_lastMelodicPitch = 0;

class Voice {
public:
  ushort m_chan;  // Index to psg channel 
  ushort m_pitch;   // current (glide-slewed) tone divisor
  ushort m_target;  // divisor of the note actually requested
  uint8_t m_noteIdx; // index into note_table, for semitone-based arpeggio
  uint16_t m_age;   // ticks since note start (delayed vibrato, sweep, retrig)
  int m_attack, m_ampl, m_ampl_top, m_decay, m_sustain, m_release, m_shape;
  static const int AMPL_MAX = 1023;
  ushort m_adsr;
  uint8_t m_partner;      // the unison twin's voice number, or NO_VOICE
  bool m_softEnv;         // decay in software; the chip's envelope is taken
  uint8_t m_envAcc;       // 1/16ths carried between ticks

  // Rates are in 1/16ths of an amplitude unit per tick, so a four second
  // segment still moves every tick instead of rounding to nothing.
  int envStep(uint16_t r) {
    uint16_t t = (uint16_t)m_envAcc + (r & 15u);
    m_envAcc = (uint8_t)(t & 15u);
    return (int)(r >> 4) + (int)(t >> 4);
  }
  ushort m_vel;

  void init (ushort chan) {
    m_chan = chan;
    m_ampl = m_sustain = 0;
    m_target = 0;
    m_noteIdx = 0;
    m_age = 0;
    kill();
  }
  
  // Works out this voice's target tone period from a MIDI note, applying
  // transpose and the current temperament. Split out of start() so a held
  // note can be retuned in place when either of those changes, instead of
  // keeping the pitch it happened to be born with.
  void setPitchFor(note_t note) {
    int n = (int)note - MIDI_MIN + (int)params[P_TRANSPOSE] - 24;
    if (n < 0) n = 0;
    if (n >= (int)N_NOTES) n = (int)N_NOTES - 1;
    m_noteIdx = (uint8_t)n;
    m_target = pgm_read_word(&note_table[n]);

    uint8_t temper = params[P_TEMPERAMENT];
    if (temper > 0 && temper < NUM_TEMPERAMENTS) {
      uint8_t root = params[P_TEMPER_ROOT];
      uint8_t pc   = (uint8_t)((((MIDI_MIN + n) % 12) + 12 - root) % 12);
      int8_t  c    = (int8_t)pgm_read_byte(&temperCents[temper][pc]);
      int8_t  c0   = (int8_t)pgm_read_byte(&temperCents[temper][0]);
      int     off  = (int)c - (int)c0;
      if (off < -TEMPER_CENT_SPAN) off = -TEMPER_CENT_SPAN;
      if (off >  TEMPER_CENT_SPAN) off =  TEMPER_CENT_SPAN;
      uint16_t factor = pgm_read_word(&temperFactor[off + TEMPER_CENT_SPAN]);
      uint32_t d = (((uint32_t)m_target * factor) + 16384UL) >> 15;
      if (d < 1) d = 1;
      if (d > 4095) d = 4095;
      m_target = (ushort)d;
    }
  }

  void start(note_t note, midictrl_t vel, midictrl_t chan) {
    // Envelope source: either the original per-MIDI-channel presets, or the
    // global custom ADSR from the parameter bank.
    ToneParams tp;
    if (params[P_ENV_MODE] == 1) {
      tp.attack  = params[P_ENV_ATTACK];
      tp.decay   = params[P_ENV_DECAY];
      tp.sustain = params[P_ENV_SUSTAIN];
      tp.rel     = params[P_ENV_RELEASE];
    } else {
      memcpy_P(&tp, &tones[chan % MAX_TONES], sizeof(ToneParams));
    }

    if (params[P_VEL_SENSE] == 0) {
      vel = 127; // velocity response off: everything at full volume
    }

    setPitchFor(note);

    // Glide: start from wherever the previous note's pitch was and slew
    // toward the target in update100Hz(). 0 = jump straight there.
    if (params[P_GLIDE] > 0 && g_lastMelodicPitch > 0) {
      m_pitch = g_lastMelodicPitch;
    } else {
      m_pitch = m_target;
    }
    g_lastMelodicPitch = m_target;
    m_age = 0;

    m_vel = 768 + (vel << 1);
    if (vel > 127) { m_vel = AMPL_MAX; m_ampl_top = AMPL_MAX; }

    // Segment rates come from a table and are TIMES, not per-tick steps.
    m_attack  = pgm_read_word(&ENV_RATE[tp.attack  > 32 ? 32 : tp.attack]);
    m_decay   = pgm_read_word(&ENV_RATE[tp.decay   > 32 ? 32 : tp.decay]);
    m_release = pgm_read_word(&ENV_RATE[tp.rel     > 32 ? 32 : tp.rel]);

    // Sustain is a fraction of the PEAK the note will reach. It used to be
    // taken from the STARTING amplitude, which differed by a factor of four
    // depending on whether attack was 1 or 2 -- so nudging attack past 1
    // quietly collapsed the sustain level.
    m_sustain = (int)(((long)m_vel * tp.sustain) >> 5);

    m_ampl  = 0;
    m_envAcc = 0;
    m_adsr  = 'A';

    psg.setTone(m_chan, m_pitch, m_ampl >> 6);
  }

  struct FXParams m_fxp;
  
  void startFX(const struct FXParams &fxp, bool softEnv = false) {
    m_fxp = fxp;
    m_softEnv = softEnv;
    m_age = 0;        // percussion is age-ranked for stealing too
  
    if (m_ampl > 0) {
      psg.setPercOff(m_chan);
    }
    m_ampl = AMPL_MAX;
    //m_ampl = 255 + (m_vel << 1);
    m_adsr = 'X';
    m_decay = fxp.timer;
    m_shape = fxp.shape;
    //m_decay = 96;


// 9 = Just release             [0]
// 4 = Reverse Release          [1]
// 8 = Repeat Release           [2]
// 12 = Reverse Repeat Release  [3]
// 10 = Repeat Release Waves    [4]
// 14 = Reverse Repeat Waves    [5]
// 11 = Release and on          [6]


  // setEnvelope() derives the chip internally via ch % 3, so m_chan can be
  // passed straight through (no need to re-decode which chip it belongs to).
    // Skipped in software mode: writing the period and shape here is exactly
    // what truncates a drum already decaying on this chip.
    if (!m_softEnv) psg.setEnvelope(m_chan, fxp.envdecay, m_shape);
#ifdef DEBUG
  Serial.print("CH: ");
  Serial.println(m_chan);
#endif
    // Amplitude 30 sets the M bit, pointing the channel at the envelope.
    // A software-envelope drum takes its level from m_ampl each tick instead.
    psg.setToneAndNoise(m_chan, fxp.tonefreq, fxp.noisefreq, m_softEnv ? 15 : 30);
  }
  

  void stop() {
    if (m_adsr == 'X') {
      //psg.setPercOff(m_chan);
      return; // Will finish when ready...
    }
      
    if (m_ampl > 0) {
      m_adsr = 'R';
    }
    
    else {
      psg.setOff(m_chan);
      //psg.setPercOff(m_chan);
    }
  }
  
  void update100Hz() {
    if (m_age < 65000) m_age++;

    // Glide: slew m_pitch toward the requested note. Proportional step so
    // big jumps move fast at first; forced +/-1 floor so it always arrives.
    if (m_adsr != 'X' && m_pitch != m_target) {
      if (params[P_GLIDE] == 0) {
        m_pitch = m_target;
      } else {
        int diff = (int)m_target - (int)m_pitch;
        int step = ((int32_t)diff * (100 - params[P_GLIDE])) / 100;
        if (step == 0) step = (diff > 0) ? 1 : -1;
        m_pitch += step;
      }
    }

   // An attack now starts from silence, so zero amplitude no longer means
   // "nothing to do" -- it is the first tick of the rise.
   if (m_ampl == 0 && m_adsr != 'A') {
      return;
    }
    
    switch(m_adsr) {
//
      case 'A':
        m_ampl += envStep(m_attack);
        if (m_ampl >= m_vel) {
          m_ampl = m_vel;
          m_envAcc = 0;
          m_adsr = 'D';
        }
        break;

      case 'D':
        // Reaching sustain used to set the level and then subtract one more
        // decay step anyway, so the held level came out low by that step and
        // depended on the Decay setting.
        m_ampl -= envStep(m_decay);
        if (m_ampl <= m_sustain) {
          m_ampl = m_sustain;
          m_envAcc = 0;
          m_adsr = (m_sustain > 0) ? 'S' : 'R';
        }
        break;

      case 'S':
        break;

      case 'R': {
        int step = envStep(m_release);
        if (m_ampl < step) m_ampl = 0;
        else m_ampl -= step;
        break;
      }

      case 'X':
        // FX is playing.
        if (m_fxp.freqdecay > 0) {
          if (m_fxp.tonefreq > 0) {
            m_fxp.tonefreq += m_fxp.freqdecay;       // pitch falls
          } else if (m_fxp.noisefreq < 16) {
            // A noise drum darkens instead, which is the same gesture: the
            // noise period is a divisor, so raising it lowers the hiss.
            uint16_t n = m_fxp.noisefreq + m_fxp.freqdecay;
            m_fxp.noisefreq = (uint8_t)(n > 15 ? 15 : n);
          }
          psg.setToneAndNoise(m_chan, m_fxp.tonefreq, m_fxp.noisefreq, 30);
        }
        
        m_ampl -= m_decay;
        
        if (m_ampl < 0) {
   
          //psg.setOff(m_chan);
          psg.setPercOff(m_chan); 
          m_ampl = 0;
        }
        return;
        
      default:
        break;
    }  

    if (m_ampl > 0) {          
      psg.setTone(m_chan, m_pitch, m_ampl >> 6);
    }
    else {
      psg.setOff(m_chan);    
      psg.setPercOff(m_chan);  
    }
  }
  
  bool isPlaying() {
    return (m_ampl > 0);
  }
  
  void kill() {
    psg.setOff(m_chan);
    psg.setPercOff(m_chan);
    m_ampl = 0;
  }
};


const ushort MAX_VOICES = 9;


static Voice voices[MAX_VOICES];

// MIDI synthesiser ---------------------------------------

// Deals with assigning note on/note off to voices

static const uint8_t PERC_CHANNEL = 9;

static const note_t
  PERC_MIN = 35,
  PERC_MAX = 59;
  
static const struct FXParams perc_params[PERC_MAX-PERC_MIN+1] PROGMEM = {
  // Mappings are from the General MIDI spec at https://www.midi.org/specifications-old/item/gm-level-1-sound-set
  
  // Params are: noisefreq, tonefreq, envdecay, freqdecay, timer, shape
  //
  // noisefreq: AY noise period. 0 = brightest hiss, 15 = darkest.
  //            16 or higher means "no noise on this voice".
  // tonefreq:  tone divisor, f = 1000000 / (16 * divisor). 0 = no tone.
  //            BIGGER divisor = LOWER pitch.
  // envdecay:  AY envelope period. Bigger = slower envelope = longer sound.
  // freqdecay: added to tonefreq each 10ms tick, so pitch falls over time.
  // timer:     amplitude decay rate; length in ms is about 10230 / timer.
  // shape:     AY envelope shape. 9 = single decay, the usual drum shape.
  
  { 9, 900, 800, 40, 50, 9 },   // 35 Acoustic bass drum
  { 16, 2000, 1500, 16, 15, 9 },  // 36 (C) 808 Bass Drum 1
  { 5, 0, 300, 0, 80, 9 },      // 37 Side Stick
  { 6, 0, 1200, 0, 30, 9  },    // 38 Acoustic snare
  
  { 16, 75, 150, 0, 60, 9 },     // 39 (D#) Clave  [GM calls 39 Hand Clap]
  { 6, 400, 1200, 11, 30, 9  }, // 40 Electric snare
  { 16, 893, 800, 20, 30, 9 },  // 41 Low floor tom   ~70Hz  (was 700)
  { 0, 0, 300, 0, 80, 9 },      // 42 Closed Hi Hat
  
  { 16, 735, 800, 13, 30, 9 },   // 43 (G) High Floor Tom ~85Hz (was 400)
  { 0, 0, 600, 0, 50, 9 },      // 44 Pedal Hi-Hat
  { 16, 625, 1400, 30, 25, 9 }, // 45 Low Tom         ~100Hz (was 800)
  { 0, 0, 800, 0, 40, 9 },      // 46 Open Hi-Hat
  
  { 16, 521, 1400, 20, 25, 9 }, // 47 (B) Low-Mid Tom ~120Hz (was 600)
  { 16, 431, 1500, 15, 22, 9 }, // 48 Hi-Mid Tom      ~145Hz (was 450)
  { 1, 0, 2500, 0, 8, 9 },      // 49 Crash Cymbal 1  (was tonal "Effect #1":
                                //    { 16, 320, 1500, 20, 22, 9 })
  { 16, 357, 1500, 10, 22, 9 }, // 50 High Tom        ~175Hz (was 300)

  { 2, 0, 1700, 0, 14, 9 },     // 51 Ride Cymbal 1
  { 0, 0, 2200, 0, 9, 9 },      // 52 Chinese Cymbal
  { 5, 71, 900, 0, 26, 9 },     // 53 Ride Bell   ~880Hz ping over noise
  { 1, 0, 420, 0, 45, 9 },      // 54 Tambourine

  { 0, 0, 1100, 0, 20, 9 },     // 55 Splash Cymbal
  { 16, 78, 600, 0, 32, 9 },    // 56 Cowbell     ~800Hz, no noise
  { 2, 0, 2300, 0, 9, 9 },      // 57 Crash Cymbal 2
  { 6, 0, 950, 0, 22, 9 },      // 58 Vibraslap

  { 3, 0, 1500, 0, 16, 9 },     // 59 Ride Cymbal 2
};
  
  

static const int REQ_MAP_SIZE = (N_NOTES+7) / 8;
static uint8_t m_requestMap[REQ_MAP_SIZE];
  // Bit is set for each note being requested
static  midictrl_t m_velocity[N_NOTES];
  // Requested velocity for each note
static  midictrl_t m_chan[N_NOTES];
  // Requested MIDI channel for each note
static uint8_t m_highest, m_lowest;
  // Highest and lowest requested notes

static const uint8_t NO_NOTE = 0xFF;
static const uint8_t PERC_NOTE = 0xFE;
static uint8_t m_playing[MAX_VOICES];
  // Which note each voice is playing

static const uint8_t NO_VOICE = 0xFF;
static uint8_t m_voiceNo[N_NOTES];
  // Which voice is playing each note
  

// --- Voice allocation ----------------------------------------------------
//
// Two things make naive allocation audible:
//
// 1. Each AY has ONE envelope generator shared by its three channels, and
//    percussion is envelope-driven. Two drums landing on the same chip fight
//    over it and the older one gets cut. So percussion prefers a chip whose
//    envelope nobody is using.
// 2. Taking a voice that is mid-attack is obvious; taking one already in its
//    release tail is nearly inaudible. So stealing is ranked, not arbitrary.

static void freeVoice(uint8_t v) {
  uint8_t idx = m_playing[v];
  if (idx != NO_NOTE && idx != PERC_NOTE) m_voiceNo[idx] = NO_VOICE;
  // Anyone pointing at this voice as their twin no longer is.
  for (uint8_t k = 0; k < MAX_VOICES; k++)
    if (voices[k].m_partner == v) voices[k].m_partner = NO_VOICE;
  voices[v].m_partner = NO_VOICE;
  m_playing[v] = NO_NOTE;
}

// A free voice, preferring one on preferChip (-1 = no preference).
static uint8_t findFreeVoice(int8_t preferChip) {
  if (preferChip >= 0) {
    for (uint8_t i = 0; i < MAX_VOICES; i++) {
      if (m_playing[i] == NO_NOTE && (int8_t)(i % 3) == preferChip) return i;
    }
  }
  for (uint8_t i = 0; i < MAX_VOICES; i++) {
    if (m_playing[i] == NO_NOTE) return i;
  }
  return NO_VOICE;
}

// A chip whose envelope generator no sounding percussion voice is using.
static int8_t freeEnvelopeChip() {
  bool used[3] = { false, false, false };
  for (uint8_t i = 0; i < MAX_VOICES; i++) {
    if (m_playing[i] == PERC_NOTE && voices[i].isPlaying()) used[i % 3] = true;
  }
  for (uint8_t c = 0; c < 3; c++) if (!used[c]) return (int8_t)c;
  return -1;
}

// Least disruptive voice to take, in preference order:
//   1. one already in its release tail  (quiet -- steal is inaudible)
//   2. the oldest percussion hit        (drums are short and nearly done)
//   3. the oldest held note that is neither the highest nor the lowest
//      (those two carry the melody and the bass line)
//   4. the oldest held note of any kind
static uint8_t pickStealVoice() {
  uint8_t  bR = NO_VOICE, bP = NO_VOICE, bM = NO_VOICE, bA = NO_VOICE;
  uint16_t aR = 0, aP = 0, aM = 0, aA = 0;

  for (uint8_t i = 0; i < MAX_VOICES; i++) {
    uint8_t idx = m_playing[i];
    if (idx == NO_NOTE) return i;            // something freed up meanwhile
    uint16_t age = voices[i].m_age;

    if (voices[i].m_adsr == 'R' && age >= aR) { bR = i; aR = age; }

    if (idx == PERC_NOTE) {
      if (age >= aP) { bP = i; aP = age; }
      continue;
    }
    if (idx != m_highest && idx != m_lowest && age >= aM) { bM = i; aM = age; }
    if (age >= aA) { bA = i; aA = age; }
  }

  if (bR != NO_VOICE) return bR;
  if (bP != NO_VOICE) return bP;
  if (bM != NO_VOICE) return bM;
  return bA;
}

// Frees a voice for reuse. Takes the channel down first so the new note
// starts from silence rather than jumping from the old note's amplitude.
static uint8_t claimVoice(int8_t preferChip) {
  uint8_t v = findFreeVoice(preferChip);
  if (v != NO_VOICE) return v;

  v = pickStealVoice();
  if (v == NO_VOICE) return NO_VOICE;
  voices[v].kill();
  freeVoice(v);
  return v;
}

static bool startNote(ushort idx) {
  uint8_t v = claimVoice(-1);
  if (v == NO_VOICE) return false;

  voices[v].start(MIDI_MIN + idx, m_velocity[idx], m_chan[idx]);
  m_playing[v] = idx;
  m_voiceNo[idx] = v;
  voices[v].m_partner = NO_VOICE;

  // Unison: a second voice on the same note, slightly off. The beating
  // between the pair is the whole point, so it is detuned by shifting the
  // tone DIVISOR rather than by transposing -- a fixed divisor offset is a
  // wider beat low down and a narrower one up high, which is how a real pair
  // of oscillators drifts. Only taken if a voice is genuinely spare: stealing
  // one to thicken a note would cost a note somewhere else.
  if (params[P_UNI_ENABLE] && m_chan[idx] != PERC_CHANNEL) {
    uint8_t u = findFreeVoice(-1);
    if (u != NO_VOICE) {
      voices[u].start(MIDI_MIN + idx, m_velocity[idx], m_chan[idx]);
      int det = (int)voices[u].m_target + (int)params[P_UNI_DETUNE];
      if (det > 4095) det = 4095;
      voices[u].m_target = (ushort)det;
      voices[u].m_pitch  = (ushort)det;
      m_playing[u] = idx;
      voices[v].m_partner = u;
      voices[u].m_partner = NO_VOICE;   // the twin owns no one
    }
  }
  return true;
}
  
// Applies the global Drums controls to one drum's parameters. Works on the
// RAM copy pulled out of PROGMEM, so the built-in kit table is untouched and
// the modifiers reshape every drum consistently.
// Shared by Drum FX Chaos and by the Warp Zone Scramble mode.
// ---------------------------------------------------------------------------
// Free RAM, measured rather than guessed
// ---------------------------------------------------------------------------
// The gap between the end of the globals and the stack is painted with a
// known byte at startup. Whatever the stack touches gets overwritten, so
// counting the bytes still holding that value afterwards gives the closest
// the stack has EVER come to the globals -- the number that actually
// matters. A stack overflow on AVR does not fault; it quietly corrupts
// globals and shows up as inexplicable misbehaviour, so this is worth
// knowing rather than inferring from the compiler's static figure.
#define RAM_CANARY 0xC5

#ifdef __AVR__
extern unsigned int __bss_end;
extern void *__brkval;

static uint8_t *ramFloor() {
  return __brkval ? (uint8_t *)__brkval : (uint8_t *)&__bss_end;
}

static void paintFreeRam() {
  uint8_t here;
  uint8_t *p = ramFloor();
  uint8_t *sp = &here;
  // Stop short of our own frame, or this would scribble on its own locals.
  while (p < sp - 16) *p++ = RAM_CANARY;
}

static int freeRamNow() {
  uint8_t here;
  return (int)(&here - ramFloor());
}

static int freeRamLow() {
  uint8_t *p = ramFloor();
  int n = 0;
  while (*p == RAM_CANARY) { p++; n++; }
  return n;
}
#else
// The emulator has a host stack; the figures would be meaningless there.
static void paintFreeRam() {}
static int  freeRamNow() { return -1; }
static int  freeRamLow() { return -1; }
#endif

// ---------------------------------------------------------------------------
// Wavetable voice
// ---------------------------------------------------------------------------
// The AY makes squares and noise and nothing else. But with tone and noise
// switched off on a channel, its amplitude register is just a 4-bit DAC
// facing the output -- so writing a waveform into it at audio rate gives a
// shape the chip cannot otherwise produce. This is the digidrum trick the
// Atari ST scene used, pointed at a held note rather than a sample.
//
// Timer3 drives it. That timer was the digidrum timer and has been free
// since that engine came out. writeReg() already runs under cli(), so an
// ISR sharing the bus with the main loop is safe.
#define WAVE_HZ 16000               // ISR rate; 1000 cycles apiece at 16MHz

static volatile uint16_t wavePhase = 0;
static volatile uint16_t waveStep  = 0;     // phase units per ISR tick
static volatile uint8_t  waveChip  = 0xFF;  // 0xFF = not running
static volatile uint8_t  waveReg   = 0;
static volatile uint8_t  waveTable = 0;
static volatile uint8_t  waveGain  = 16;    // 0..16: Level times the ADSR
static uint8_t waveVoice = NO_VOICE;   // which voice the ISR has taken over
static void applyWavetable();          // noteOn calls this before it is defined

// One ISR tick: advance the phase, look up the sample, push it at the chip.
// Deliberately small -- no arithmetic beyond an add and a shift.
static inline void waveTick() {
  if (waveChip == 0xFF) return;
  wavePhase += waveStep;
  uint8_t idx = (uint8_t)(wavePhase >> 10) & (WAVE_LEN - 1);
  uint8_t v = pgm_read_byte(&WAVE_TABLES[waveTable][idx]);
  // Scale by the voice's current envelope. Without this the waveform played
  // flat out until the note ended while every other voice breathed, which is
  // why a square voice alongside it sounded like the one with the envelope.
  // A multiply and a shift; no divide, this is an interrupt.
  v = (uint8_t)(((uint16_t)v * waveGain) >> 4);
  writeReg(waveChip, waveReg, v);
}

#ifdef __AVR__
ISR(TIMER3_COMPA_vect) { waveTick(); }

static void waveTimerInit() {
  TCCR3A = 0;
  TCCR3B = (1 << WGM32) | (1 << CS31);          // CTC, /8 prescale
  OCR3A  = (uint16_t)((F_CPU / 8UL / WAVE_HZ) - 1UL);
  TIMSK3 = 0;                                   // enabled only when in use
}
static inline void waveTimerRun(bool on) {
  if (on) TIMSK3 |= (1 << OCIE3A);
  else    TIMSK3 &= ~(1 << OCIE3A);
}
#else
// The emulator calls waveTick() from its render loop at the same rate.
extern "C" void emu_wave_tick() { waveTick(); }
static void waveTimerInit() {}
static inline void waveTimerRun(bool) {}
#endif

static uint16_t warpRngState = 0xACE1;

// Depth is a magnitude, 1..63, and every mode should respond to it evenly.
// It used to be read differently in each one -- as a raw bit pattern in
// Stutter, a shift in Scramble, and not at all in Sync Buzz -- which is why
// the control felt skewed and in places did nothing.
static inline uint8_t warpScale(uint8_t depth, uint8_t maxv) {
  return (uint8_t)(((uint16_t)depth * maxv + 31u) / 63u);
}

// Which mixer bits Stutter gates as depth rises: tone then noise, chip by
// chip, so it thickens evenly instead of jumping around.
static const uint8_t STUTTER_ORDER[6] PROGMEM = { 0, 3, 1, 4, 2, 5 };

static uint8_t warpRand() {
  warpRngState ^= warpRngState << 7;
  warpRngState ^= warpRngState >> 9;
  warpRngState ^= warpRngState << 8;
  return (uint8_t)warpRngState;
}

static void applyDrumMods(FXParams &f) {
  uint8_t tune = params[P_DRUM_TUNE];              // 50..200 %
  uint8_t len  = params[P_DRUM_DECAY];             // 50..200 %
  uint8_t bend = params[P_DRUM_BEND];              // 0..200 %
  int8_t  nz   = (int8_t)params[P_DRUM_NOISE] - 7; // -7..+7

  // Pitch. tonefreq is a DIVISOR, so a higher tune % must make it smaller.
  if (tune != 100) {
    if (f.tonefreq > 0) {
      uint32_t d = ((uint32_t)f.tonefreq * 100UL) / tune;
      if (d < 1) d = 1;
      if (d > 4095) d = 4095;
      f.tonefreq = (ushort)d;
    } else if (f.noisefreq < 16) {
      // Half the kit -- snare, every hat and cymbal, tambourine, side stick
      // -- has no tone at all, so Tune did nothing to any of them. For those
      // the noise period is the pitch. It is shifted rather than scaled:
      // the range is sixteen integers and the hats already sit at 0, where
      // a ratio can only move them one step and the chip cannot tell 0 from
      // 1 anyway. A shift gives the whole range in both directions.
      int shift = ((int)100 - (int)tune) * 7 / 100;    // +7 dark .. -7 bright
      int n = (int)f.noisefreq + shift;
      if (n < 0) n = 0;
      if (n > 15) n = 15;
      f.noisefreq = (uint8_t)n;
    }
  }

  // Length. The envelope period stretches, and the amplitude decay rate
  // shrinks (length is roughly 10230/timer ms), so both ends agree.
  if (len != 100) {
    uint32_t e = ((uint32_t)f.envdecay * len) / 100UL;
    if (e > 65535UL) e = 65535UL;
    f.envdecay = (ushort)e;
    uint32_t t = ((uint32_t)f.timer * 100UL) / len;
    if (t < 1) t = 1;
    f.timer = (ushort)t;
  }

  // Pitch drop. On a tone drum this is added to the divisor each tick. On a
  // noise drum there is no divisor to add to, so Bend could not touch a
  // snare or a hat; freqdecay there means "darken the noise as it decays",
  // handled in the percussion tick.
  if (bend != 100) {
    f.freqdecay = (ushort)(((uint32_t)f.freqdecay * bend) / 100UL);
  }
  if (f.tonefreq == 0 && f.noisefreq < 16 && bend > 100) {
    // Nothing to scale, so give it a sweep proportional to how far past
    // 100% the control has been pushed.
    uint16_t sweep = (uint16_t)((bend - 100) / 25);       // 0..4
    if (sweep > 0) f.freqdecay = sweep;
  }

  // Noise colour. Entries at 16 or above mean "no noise" to
  // setToneAndNoise(), so leave those alone or a shift would switch noise on.
  if (f.noisefreq < 16 && nz != 0) {
    int v = (int)f.noisefreq + nz;
    if (v < 0) v = 0;
    if (v > 15) v = 15;
    f.noisefreq = (ushort)v;
  }

  // Reverse: AY shape 13 ramps UP and holds, so the hit swells instead of
  // decaying; the voice's own amplitude timer then cuts it off. Shape 9,
  // which every kit entry uses, is the ordinary single decay.
  if (params[P_DRUM_REVERSE]) {
    f.shape = 13;
  }

  // Chaos: vary this strike. Drum machines are identical every hit; real
  // kits are not. Pitch up to +/-50%, noise a few shades either way, length
  // up to +/-25%, all scaled by the control.
  uint8_t chaos = params[P_DRUM_CHAOS];
  if (chaos) {
    int8_t r1 = (int8_t)(warpRand() & 0x3F) - 32;   // -32..+31
    int8_t r2 = (int8_t)(warpRand() & 0x0F) - 8;
    int8_t r3 = (int8_t)(warpRand() & 0x3F) - 32;

    if (f.tonefreq > 0) {
      int32_t d = ((int32_t)f.tonefreq * r1 * chaos) / 4032;
      int32_t np = (int32_t)f.tonefreq + d;
      if (np < 1) np = 1;
      if (np > 4095) np = 4095;
      f.tonefreq = (ushort)np;
    }
    if (f.noisefreq < 16) {
      int v = (int)f.noisefreq + ((int)r2 * chaos) / 126;
      if (v < 0) v = 0;
      if (v > 15) v = 15;
      f.noisefreq = (ushort)v;
    }
    int32_t t = (int32_t)f.timer + ((int32_t)f.timer * r3 * chaos) / 8064;
    if (t < 1) t = 1;
    if (t > 65535) t = 65535;
    f.timer = (ushort)t;
  }
}

// Flam: one pending repeat is enough -- a second hit landing before the
// first flam fires just replaces it, which is what a drummer does anyway.
static note_t  flamNote  = 0;
static uint8_t flamTicks = 0;
static bool    flamFiring = false;   // stops a flam from scheduling a flam

static bool startPercussion(note_t note) {
  if (note < PERC_MIN || note > PERC_MAX) return false;

  // Prefer a chip whose envelope generator is idle, so this hit does not cut
  // short a drum already sounding on the same chip.
  const int8_t chip = freeEnvelopeChip();
  uint8_t v = claimVoice(chip);
  if (v == NO_VOICE) return false;

  FXParams fxp;
  memcpy_P(&fxp, &perc_params[note - PERC_MIN], sizeof(FXParams));
  applyDrumMods(fxp);
  // One envelope generator per chip, shared by its three channels. A drum
  // landing on a chip whose envelope is already running would overwrite the
  // period and restart it, cutting the drum that was there. Hats show this
  // worst: they are the most frequent hit and carry the shortest period in
  // the kit, so a hat on a ringing crash drops 2500 to 300 and truncates it
  // eightfold. When no chip is free the new drum decays in software instead,
  // which is coarser but disturbs nothing.
  voices[v].startFX(fxp, chip < 0);
  m_playing[v] = PERC_NOTE;

  if (params[P_DRUM_FLAM] > 0 && !flamFiring) {
    flamNote  = note;
    flamTicks = params[P_DRUM_FLAM];
  }
  return true;
}
    
static bool stopNote(ushort idx) {
  uint8_t v = m_voiceNo[idx];
  if (v != NO_VOICE && m_playing[v] != NO_NOTE) {
    // Release the twin first, or it would be left ringing with nothing
    // pointing at it -- m_voiceNo only ever knows about the lead voice.
    uint8_t u = voices[v].m_partner;
    if (u != NO_VOICE && u < MAX_VOICES && m_playing[u] == idx) {
      voices[u].stop();
      m_playing[u] = NO_NOTE;
      voices[u].m_partner = NO_VOICE;
    }
    voices[v].m_partner = NO_VOICE;
    voices[v].stop();
    m_playing[v] = NO_NOTE;
    m_voiceNo[idx] = NO_VOICE;
    return true;
  }
  return false;
}

static void updateRequestedNotes() {
  m_highest = m_lowest = NO_NOTE;
  ushort i,j;
    
  // Check highest requested note is playing
  // Return true if note was restarted; false if already playing 
  for (i = 0; i < REQ_MAP_SIZE; i++) {
    uint8_t req = m_requestMap[i];
    if (req == 0) {
      continue;
    }

    for (j = 0; j < 8; j++) {
      if (req & (1 << j)) {
        ushort idx = i*8 + j;
        if (m_lowest == NO_NOTE || m_lowest > idx) {
          m_lowest = idx;
        }
        if (m_highest==NO_NOTE || m_highest < idx)  {
          m_highest = idx;
        }
      }
    }
  }
}

static bool restartANote() {
  if (m_highest != NO_NOTE && m_voiceNo[m_highest] == NO_VOICE) {
    return startNote(m_highest);
  }

  if (m_lowest != NO_NOTE && m_voiceNo[m_lowest] == NO_VOICE) {
    return startNote(m_lowest);
  }

  return false;
}

static void synth_init () {
  ushort i;

  for (i = 0; i < REQ_MAP_SIZE; i++) {
    m_requestMap[i] = 0;
  }

  for (i = 0; i < N_NOTES; i++) {
    m_velocity[i] = 0;
    m_voiceNo[i] = NO_VOICE;
  }
    
  for (i = 0; i < MAX_VOICES; i++) {
    m_playing[i] = NO_NOTE;
  }
    
  m_highest = m_lowest = NO_NOTE;
}

static void noteOff(midictrl_t chan, note_t note, midictrl_t vel) {
  if (chan == PERC_CHANNEL || note < MIDI_MIN || note > MIDI_MAX) {
    return; // Just ignore it
  }

    if (note < MIDI_MIN || note > MIDI_MAX) {
    return; // Just ignore it
  }

  ushort idx = note - MIDI_MIN;

  m_requestMap[idx/8] &= ~(1 << (idx & 7));
  m_velocity[idx] = 0;
  updateRequestedNotes();
    
  if (stopNote(idx)) {
    restartANote();
  }
}

static void noteOn(midictrl_t chan, note_t note, midictrl_t vel) {
  if (vel == 0) {
    noteOff(chan, note, 0);
    return;
  }

  if (chan == PERC_CHANNEL) {
    // This used to call stopOneNote() first, unconditionally, so EVERY drum
    // hit silenced a melodic note even when voices were free. Allocation now
    // steals only when it actually has to.
    startPercussion(note);
    return;
  }
    
  // Regular note processing now
    
  if (note < MIDI_MIN || note > MIDI_MAX) {
    return; // Just ignore it
  }

  ushort idx = note - MIDI_MIN;
    
  if (m_voiceNo[idx] != NO_VOICE) {
    return; // Already playing. Ignore this request.
  }

  m_requestMap[idx/8] |= 1 << (idx & 7);
  m_velocity[idx] = vel;
  m_chan[idx] = chan;
  updateRequestedNotes();
    
  startNote(idx);   // claimVoice() handles stealing internally

  // Hand the note to the wavetable straight away. Waiting for the next
  // 100Hz tick delayed the start of every wavetable note by up to 10ms,
  // which reads as the voice lagging behind the keyboard.
  if (params[P_WAVE_ENABLE]) applyWavetable();
}
  
  
// --- Effects engine + serial parameter protocol --------------------------
//
// Everything here is driven by the params[] bank (see parameters.h, which
// generate.py produces alongside the web panel). The panel talks over the
// Leonardo's USB-CDC serial port -- a separate USB interface from USB-MIDI
// and from Serial1's DIN MIDI, so all three coexist.
//
// Protocol (ASCII, one command per line):
//   P:<idx>:<value>    set one parameter     -> V:<idx>:<clamped value>
//   DUMP               request all values    -> PRESET:v0,v1,...
//   LOAD:v0,v1,...     apply a full preset   -> PRESET:v0,v1,...
//   SAVE               persist to EEPROM     -> SAVED:1
//   DEFAULTS           restore defaults      -> PRESET:v0,v1,...
// Unrecognised lines (e.g. #ifdef DEBUG logging sharing the port) are
// ignored; the panel only acts on PRESET:/V:/SAVED: replies.

static uint8_t  vibPhase = 0;       // 0..255, wraps
static uint16_t vibPhaseStep = 13;
static uint8_t  tremPhase = 0;
static uint16_t tremPhaseStep = 10;

// 32-point sine table, one full cycle, range approx -127..127.
// Shared by the vibrato and tremolo LFOs.
static const int8_t lfoSine[32] PROGMEM = {
    0,  25,  49,  71,  90, 106, 117, 125,
  127, 125, 117, 106,  90,  71,  49,  25,
    0, -25, -49, -71, -90,-106,-117,-125,
 -127,-125,-117,-106, -90, -71, -49, -25
};

static uint32_t warpIntervalUs = 1000;

static void recalcDerived() {
  // Tick rate is ~100Hz: phase steps (256 per cycle) needed per tick
  // = rateHz * 256 / 100 = rateX10 * 256 / 1000.
  vibPhaseStep = (uint16_t)(((uint32_t)params[P_VIB_RATE] * 256UL) / 1000UL);
  if (vibPhaseStep == 0) vibPhaseStep = 1;
  tremPhaseStep = (uint16_t)(((uint32_t)params[P_TREM_RATE] * 256UL) / 1000UL);
  if (tremPhaseStep == 0) tremPhaseStep = 1;

  // Warp rate 1..120 maps to a 30ms..250us tick, i.e. ~33Hz slow chopping
  // up to ~4kHz, where the effect stops being rhythmic and becomes timbre.
  warpIntervalUs = 30000UL / params[P_WARP_RATE];
  if (warpIntervalUs < 250UL) warpIntervalUs = 250UL;

  // Clock Warp leaves the master clock wherever it stopped, so put it back
  // whenever that mode is not the one running.
  if (params[P_WARP_MODE] != 10) {
    uint8_t sreg = SREG;
    cli();
    OCR1AH = 0;
    OCR1AL = DIVISOR;
    SREG = sreg;
  }

  // Retune anything already sounding. Transpose and temperament used to be
  // read once when a note started, so a held chord kept whatever tuning it
  // was born with and changing either did nothing until the next note.
  // m_playing holds the note index, so the original MIDI note is recoverable.
  for (uint8_t v = 0; v < MAX_VOICES; v++) {
    uint8_t idx = m_playing[v];
    if (idx == NO_NOTE || idx == PERC_NOTE) continue;
    voices[v].setPitchFor((note_t)(MIDI_MIN + idx));
  }

  // Any parameter change resyncs the chips, which also cleans up whatever
  // the Warp Zone scribbled directly into the hardware.
  psg.invalidate();
}

// Tracks which chip/sub-channel currently has the envelope-mode bit set,
// so it can be cleared cleanly when the buzz target moves elsewhere.
static int8_t g_buzzChip = -1, g_buzzSub = -1;

// Hands the highest held note to the wavetable, or gives it back. Runs on
// the 100Hz tick beside the other voice housekeeping.
static void applyWavetable() {
  int8_t target = -1;
  if (params[P_WAVE_ENABLE] && m_highest != NO_NOTE) {
    uint8_t v = m_voiceNo[m_highest];
    if (v != NO_VOICE && m_playing[v] != PERC_NOTE && voices[v].isPlaying()) target = v;
  }

  if (target < 0) {
    if (waveChip != 0xFF) {
      waveTimerRun(false);
      uint8_t c = waveChip, r = waveReg;
      waveChip = 0xFF;
      waveVoice = NO_VOICE;
      writeReg(c, r, 0);            // leave the channel silent, not stuck
      psg.invalidate();             // and let the cache rewrite it properly
    }
    return;
  }

  const uint8_t chip = (uint8_t)(target % 3), sub = (uint8_t)(target / 3);

  // Tone and noise off, through the cache so it survives an invalidate.
  psg.regs[chip][PSGRegs::MIXER] |= (uint8_t)((1u << sub) | (8u << sub));

  // Phase step: at WAVE_HZ, a table of WAVE_LEN entries with a 10-bit
  // fractional phase steps by (freq * 65536 / WAVE_HZ). The note's frequency
  // is clock/(16*TP), so that folds to a single divide.
  uint16_t tp = voices[target].m_pitch;
  if (tp < 1) tp = 1;
  // Rounded, not truncated: at the bottom of the range one phase unit is
  // worth nearly forty cents, and truncating always lost it.
  uint32_t step = (256000UL + (tp / 2)) / tp;
  if (step < 1) step = 1;
  if (step > 65535UL) step = 65535UL;

  waveTable = (uint8_t)(params[P_WAVE_SHAPE] % WAVE_COUNT);
  // Level and the envelope fold into one 0..16 gain, worked out here at
  // 100Hz rather than in the interrupt.
  {
    int amp = voices[target].m_ampl >> 6;          // 0..15
    if (amp < 0) amp = 0;
    if (amp > 15) amp = 15;
    uint16_t g = ((uint16_t)params[P_WAVE_LEVEL] * (uint16_t)amp * 16u) / 225u;
    waveGain = (uint8_t)(g > 16 ? 16 : g);
  }
  waveReg   = (uint8_t)(PSGRegs::TONEAAMPL + sub);
  waveStep  = (uint16_t)step;
  waveChip  = chip;
  waveVoice = (uint8_t)target;
  waveTimerRun(true);
}

static void applyBuzzyBass() {
  int8_t targetVoice = -1;

  if (params[P_BUZZ_ENABLE] && m_lowest != NO_NOTE) {
    uint8_t v = m_voiceNo[m_lowest];
    if (v != NO_VOICE && m_playing[v] != PERC_NOTE && voices[v].isPlaying()) {
      targetVoice = v;
    }
  }

  int8_t newChip = -1, newSub = -1;
  if (targetVoice >= 0) {
    newChip = targetVoice % 3;
    newSub  = targetVoice / 3;
  }

  if ((newChip != g_buzzChip || newSub != g_buzzSub) && g_buzzChip >= 0) {
    psg.clearBuzz(g_buzzChip, g_buzzSub);
  }

  if (newChip >= 0) {
    psg.applyBuzz(newChip, newSub, voices[targetVoice].m_pitch,
                  params[P_BUZZ_RATIO],
                  pgm_read_byte(&buzzShapes[params[P_BUZZ_SHAPE] & 3]),
                  (int8_t)((int)params[P_BUZZ_DETUNE] - 32));
  }

  g_buzzChip = newChip;
  g_buzzSub  = newSub;
}

// --- Warp Zone: digitally controlled circuit bending ---------------------
//
// A hardware bend works by forcing the chip into states the data sheet does
// not cover, while it is mid-note. These modes do the same thing in
// software: they write STRAIGHT to the chips with writeReg(), bypassing the
// register cache, while the normal 100Hz voice updates keep writing the
// "correct" values through the cache. The two fight, and that fight is the
// sound. recalcDerived() calls psg.invalidate(), so changing any parameter
// (including turning Warp back Off) forces a clean resync.
//
// HARDWARE SAFETY: registers 14 and 15 are the parallel I/O port data
// registers, and mixer bits 6-7 set those ports' direction. psg.init()
// leaves both ports configured as OUTPUTS, so anything that grounds an I/O
// pin while the chip drives it high is a short through the output driver.
// Nothing below ever touches R14/R15 or mixer bits 6-7.

// Arpeggio chord shapes, semitone offsets, 3 steps each. Indexed by
// P_ARP_MODE - 1 (mode 0 is Off). Cycling these fast enough is what makes a
// single AY channel read as a chord.
static const int8_t arpTable[6][3] PROGMEM = {
  {  0,  4,  7 },  // Maj
  {  0,  3,  7 },  // Min
  {  0, 12,  0 },  // Oct
  {  0,  7, 12 },  // 5th
  {  0,  3,  6 },  // Dim
  {  0,  7, 16 }   // Wide
};

static uint8_t arpStep = 0;
static uint8_t arpTickCount = 0;


// Registers the Scramble mode is allowed to hit: tone periods, noise
// period, amplitudes and the envelope. Never R14/R15.
static const uint8_t warpVictims[] PROGMEM = {
  PSGRegs::TONEAHIGH, PSGRegs::TONEBHIGH, PSGRegs::TONECHIGH,
  PSGRegs::TONEALOW,  PSGRegs::TONEBLOW,  PSGRegs::TONECLOW,
  PSGRegs::NOISEGEN,  PSGRegs::TONEAAMPL, PSGRegs::TONEBAMPL,
  PSGRegs::TONECAMPL, PSGRegs::ENVLOW,    PSGRegs::ENVHIGH,
  PSGRegs::ENVSHAPE
};
static const uint8_t N_WARP_VICTIMS = sizeof(warpVictims);

// Master noise gate. The AY has no noise level: tone and noise share one
// amplitude register per channel. What it does have is a per-channel
// noise-ENABLE bit, so switching that on and off faster than the ear
// resolves trades duty cycle for level. The duty is randomised rather than
// periodic -- a regular gate at a few kHz parks a whine right in the
// spectrum, while a random one spreads the artefact across it, which on a
// noise source is inaudible.
static const uint32_t NOISE_GATE_US = 250;   // 4kHz
static unsigned long lastNoiseUs = 0;

static void noiseGateTick() {
  uint8_t lvl = params[P_MIX_NOISE];
  if (lvl >= 15) return;                     // fully open: nothing to do
  bool on = lvl > 0 && ((warpRand() % 15) < lvl);
  for (uint8_t c = 0; c < 3; c++) {
    uint8_t m = psg.regs[c][PSGRegs::MIXER];
    // bits 3-5 are the noise-enable bits, active low. Setting them mutes
    // noise on all three channels; bits 6-7 (I/O direction) stay untouched.
    writeReg(c, PSGRegs::MIXER, on ? m : (uint8_t)(m | 0x38));
  }
}

static uint8_t  warpPhase = 0;
static uint16_t warpRamp = 0;        // slow sawtooth for the motion modes
// 16-bit, because an 8-bit phase wrapped in a fraction of a second: at the
// useful Motion settings the rate was wobbling 4-10 times a second, which
// averages out and sounds like nothing is happening. The whole point is a
// slow hand on a fader, so the accumulator is wider and the step scaled to
// give sweeps from about half a second up to half a minute.
static uint16_t warpMotionPhase = 0;
#define WARP_MOTION_SCALE 20

static void warpTick() {
  uint8_t mode = params[P_WARP_MODE];
  if (mode == 0) return;

  uint8_t depth = params[P_WARP_DEPTH];
  warpPhase++;
  warpRamp++;

  switch (mode) {

    case 1: { // Sync Buzz -- rewriting R13 restarts the envelope from the
              // top. Done at audio rate against a sounding note this is the
              // Atari "sync buzzer": hard-sync style harmonics.
              //
              // Restarting the envelope is only audible on a channel whose
              // volume actually follows the envelope, so force the M bit
              // (0x10) onto any channel that is currently sounding. Without
              // this the mode does nothing unless Buzzy Bass is already on.
      uint8_t want = 1 + warpScale(depth, 8);     // 1..9 channels
      uint8_t taken = 0;
      for (uint8_t c = 0; c < 3; c++) {
        bool touched = false;
        for (uint8_t sub = 0; sub < 3 && taken < want; sub++) {
          uint8_t a = psg.regs[c][PSGRegs::TONEAAMPL + sub];
          if (a == 0) continue;
          writeReg(c, PSGRegs::TONEAAMPL + sub, a | 0x10);
          taken++;
          touched = true;
        }
        if (touched) writeReg(c, PSGRegs::ENVSHAPE, psg.regs[c][PSGRegs::ENVSHAPE]);
      }
      break;
    }

    case 2: { // Stutter -- gate tone/noise on and off at the mixer. Bits
              // 6-7 (I/O direction) are carried through untouched.
      uint8_t n = 1 + warpScale(depth, 5);        // 1..6 sources gated
      uint8_t patt = 0;
      for (uint8_t i = 0; i < n; i++) patt |= (1 << pgm_read_byte(&STUTTER_ORDER[i]));
      if (!(warpPhase & 1)) patt = 0;
      for (uint8_t c = 0; c < 3; c++) {
        uint8_t m = psg.regs[c][PSGRegs::MIXER];
        writeReg(c, PSGRegs::MIXER, ((m ^ patt) & 0x3F) | (m & 0xC0));
      }
      break;
    }

    case 3: { // Scramble -- the closest thing to a physical bend: junk into
              // a random audio register on a random chip.
      uint8_t hits = 1 + warpScale(depth, 3);     // 1..4 registers per tick
      // Depth also decides how far a value is allowed to move: at the bottom
      // only the low bits are disturbed, at the top the whole byte is. That
      // gives a continuous slide from a wobble to complete chaos, rather
      // than four steps and nothing in between.
      uint8_t width = (uint8_t)((1u << (1 + warpScale(depth, 7))) - 1u);
      for (uint8_t n = 0; n < hits; n++) {
        uint8_t c   = warpRand() % 3;
        uint8_t reg = pgm_read_byte(&warpVictims[warpRand() % N_WARP_VICTIMS]);
        uint8_t val = (uint8_t)((psg.regs[c][reg] & ~width) | (warpRand() & width));
        if (reg == PSGRegs::MIXER) {  // never reachable today, but stays
          val = (val & 0x3F) | (psg.regs[c][PSGRegs::MIXER] & 0xC0);
        }
        if (reg == PSGRegs::TONEAAMPL || reg == PSGRegs::TONEBAMPL ||
            reg == PSGRegs::TONECAMPL) {
          val &= 0x1F;               // keep amplitude in range, allow M bit
        }
        writeReg(c, reg, val);
      }
      break;
    }

    case 5: { // Tape Stop -- stretch every tone period further and further,
              // so pitch sags to a halt, then snaps back. The drag is the
              // whole point; where it lands is nothing.
      uint16_t peak = pgm_read_word(&WARP_STRETCH[depth & 63]);
      uint16_t stretch = 256 + (uint16_t)(((uint32_t)(peak - 256) * (warpRamp & 0x3FF)) / 1023u);
      uint8_t c = warpPhase % 3;      // one chip per tick, to bound CPU
      for (uint8_t sub = 0; sub < 3; sub++) {
        uint8_t lo = PSGRegs::TONEALOW + (sub << 1);
        uint16_t per = psg.regs[c][lo] | ((uint16_t)psg.regs[c][lo + 1] << 8);
        if (!per) continue;
        uint32_t np = ((uint32_t)per * stretch) >> 8;
        if (np > 4095) np = 4095;
        writeReg(c, lo, np & 0xFF);
        writeReg(c, lo + 1, np >> 8);
      }
      break;
    }

    case 6: { // Siren -- sweep every tone period up and down continuously.
      uint8_t t = warpRamp & 0x7F;
      if (t > 63) t = 127 - t;                    // triangle 0..63..0
      uint16_t peak = pgm_read_word(&WARP_STRETCH[depth & 63]);
      uint16_t mul = 256 + (uint16_t)(((uint32_t)(peak - 256) * t) / 63u);
      uint8_t c = warpPhase % 3;
      for (uint8_t sub = 0; sub < 3; sub++) {
        uint8_t lo = PSGRegs::TONEALOW + (sub << 1);
        uint16_t per = psg.regs[c][lo] | ((uint16_t)psg.regs[c][lo + 1] << 8);
        if (!per) continue;
        uint32_t np = ((uint32_t)per * mul) >> 8;
        if (np > 4095) np = 4095;
        writeReg(c, lo, np & 0xFF);
        writeReg(c, lo + 1, np >> 8);
      }
      break;
    }

    case 7: { // Crush -- mask off progressively more of the tone period's
              // low bits, so pitch quantises to a coarser and coarser grid.
              // Sounds like the resolution itself is failing.
      // Depth sets how coarse the grid gets at the peak of the sweep; below
      // depth 9 the old expression masked no bits at all and did nothing.
      uint8_t peakBits = 1 + warpScale(depth, 6);           // 1..7
      uint8_t bits = (uint8_t)(((uint16_t)(warpRamp & 0xFF) * peakBits) / 255u);
      if (bits > 7) bits = 7;
      uint8_t mask = (uint8_t)(0xFF << bits);
      uint8_t c = warpPhase % 3;
      for (uint8_t sub = 0; sub < 3; sub++) {
        uint8_t lo = PSGRegs::TONEALOW + (sub << 1);
        uint8_t v = psg.regs[c][lo] & mask;
        writeReg(c, lo, v);
      }
      break;
    }

    case 9: {   // Env Crush -- the same quantising applied to the envelope
                // period, so decays and buzz tones stair-step rather than
                // the pitch. Different flavour, same gesture.
      // Envelope periods run into the thousands, where the tone crush's
      // range of a few bits changes them by under two per cent -- which is
      // why this did nothing at all. It needs to reach twelve bits before
      // the period snaps somewhere audibly different. The sweep also starts
      // from half depth rather than zero, so the effect is always doing
      // something instead of passing through untouched for half its cycle.
      uint8_t peakBits  = 5 + warpScale(depth, 7);        // 5..12
      uint8_t floorBits = (uint8_t)(peakBits / 2);
      uint8_t bits = (uint8_t)(floorBits +
        (((uint16_t)(warpRamp & 0xFF) * (uint16_t)(peakBits - floorBits)) / 255u));
      if (bits > 12) bits = 12;
      uint16_t emask = (uint16_t)(~((1u << bits) - 1u));
      for (uint8_t c = 0; c < 3; c++) {
        uint16_t e = (uint16_t)psg.regs[c][PSGRegs::ENVLOW] |
                     ((uint16_t)psg.regs[c][PSGRegs::ENVHIGH] << 8);
        if (!e) continue;
        uint16_t q = (uint16_t)(e & emask);
        if (q < 1) q = 1;
        writeReg(c, PSGRegs::ENVLOW,  (uint8_t)(q & 0xFF));
        writeReg(c, PSGRegs::ENVHIGH, (uint8_t)(q >> 8));
      }
      break;
    }

    case 10: {  // Clock Warp -- wobble the AY master clock itself. The
                // Leonardo generates it on Timer1, so this sits upstream of
                // all three chips: pitch, noise colour, envelope rates and
                // drum decays all move together. That is vari-speed rather
                // than a pitch shift, and nothing downstream can imitate it.
      int8_t m = (int8_t)pgm_read_byte(&lfoSine[(warpRamp >> 2) & 31]);
      int16_t swing = ((int16_t)m * (int16_t)warpScale(depth, 5)) / 127;
      int d = (int)DIVISOR + (int)swing;
      // The AY-3-8910 is rated to 2MHz. Stopping at 1.6MHz leaves headroom
      // for forty-year-old parts rather than running them at the limit for
      // the sake of an effect; downward there is no such constraint.
      if (d < 4) d = 4;            // 1.6MHz
      if (d > 20) d = 20;          // 380kHz, a deep sag
      uint8_t sreg = SREG;
      cli();
      OCR1AH = 0;
      OCR1AL = (uint8_t)d;         // 16-bit register: high byte first
      SREG = sreg;
      break;
    }

    case 8: { // Ring -- flip each channel's amplitude between its real value
              // and a cut one at audio rate. That is amplitude modulation,
              // and it gives the metallic ring-mod clang the AY has no
              // hardware for.
      uint8_t c = warpPhase % 3;
      bool low = (warpPhase & 1);
      for (uint8_t sub = 0; sub < 3; sub++) {
        uint8_t a = psg.regs[c][PSGRegs::TONEAAMPL + sub];
        if (a & 0x10) continue;            // envelope-driven: leave alone
        uint8_t cut = warpScale(depth, 15);
        uint8_t v = low ? (uint8_t)(a > cut ? a - cut : 0) : a;
        writeReg(c, PSGRegs::TONEAAMPL + sub, v & 0x0F);
      }
      break;
    }

    case 4: { // Zap -- rip the noise period up and down. Classic arcade
              // laser/explosion sweep.
              //
              // Sweeping the noise period is silent unless noise is routed
              // to a channel, so clear the mixer's noise-disable bits (3-5,
              // active low) as well. Tone bits 0-2 and the I/O direction
              // bits 6-7 are carried through untouched.
      uint8_t v = warpPhase & 0x1F;
      if (v > 15) v = 31 - v;            // triangle 0..15..0
      v = (uint8_t)(((uint16_t)v * warpScale(depth, 15)) / 15);
      for (uint8_t c = 0; c < 3; c++) {
        writeReg(c, PSGRegs::MIXER, psg.regs[c][PSGRegs::MIXER] & 0xC7);
        writeReg(c, PSGRegs::NOISEGEN, v);
      }
      break;
    }
  }
}

// Identifies which generated parameter layout this firmware was built
// against. The panel compares it to its own and complains loudly on a
// mismatch -- otherwise a stale flash just misroutes every P:<idx> write to
// whatever parameter used to live at that index, with no error anywhere.
static void sendLayout() {
  Serial.print(F("LAYOUT:"));
  Serial.print(PARAM_LAYOUT_VERSION, HEX);
  Serial.print(',');
  Serial.println(NUM_PARAMS);
}

// Maps an incoming CC onto a parameter, or binds it if the panel has armed
// MIDI learn. The reply is the same V:<idx>:<value> line a panel edit
// produces, so turning a knob on a controller moves the on-screen control.
static void handleControlChange(uint8_t cc, uint8_t value) {
  if (ccLearnTarget != CC_NONE) {
    uint8_t target = ccLearnTarget;
    ccLearnTarget = CC_NONE;
    // Free the CC from whatever else held it, so one control cannot end up
    // driving two parameters at once.
    for (uint8_t i = 0; i < NUM_PARAMS; i++) if (ccMap[i] == cc) ccMap[i] = CC_NONE;
    ccMap[target] = cc;
    Serial.print(F("CC:"));
    Serial.print(target);
    Serial.print(':');
    Serial.println(cc);
    return;
  }

  for (uint8_t i = 0; i < NUM_PARAMS; i++) {
    if (ccMap[i] != cc) continue;
    // 0..127 spread across the parameter's own range.
    int lo = pgm_read_byte(&PARAM_MIN[i]);
    int hi = pgm_read_byte(&PARAM_MAX[i]);
    int v  = lo + (((int)value * (hi - lo)) + 63) / 127;
    setParam(i, v);
    recalcDerived();
    Serial.print(F("V:"));
    Serial.print(i);
    Serial.print(':');
    Serial.println(params[i]);
    return;
  }
}

static void sendPreset() {
  Serial.print(F("PRESET:"));
  for (uint8_t i = 0; i < NUM_PARAMS; i++) {
    Serial.print(params[i]);
    if (i < NUM_PARAMS - 1) Serial.print(',');
  }
  Serial.println();
}

static void handleCommand(char *cmd) {
  if (strncmp(cmd, "P:", 2) == 0) {
    char *sep = strchr(cmd + 2, ':');
    if (!sep) return;
    uint8_t idx = (uint8_t)atoi(cmd + 2);
    if (idx >= NUM_PARAMS) return;
    setParam(idx, atoi(sep + 1));
    recalcDerived();
    Serial.print(F("V:"));
    Serial.print(idx);
    Serial.print(':');
    Serial.println(params[idx]);
  }
  else if (strncmp(cmd, "LEARN:", 6) == 0) {
    uint8_t idx = (uint8_t)atoi(cmd + 6);
    if (idx < NUM_PARAMS) {
      ccLearnTarget = idx;
      Serial.print(F("LEARNING:"));
      Serial.println(idx);
    }
  }
  else if (strncmp(cmd, "UNLEARN:", 8) == 0) {
    uint8_t idx = (uint8_t)atoi(cmd + 8);
    if (idx < NUM_PARAMS) {
      ccMap[idx] = CC_NONE;
      Serial.print(F("CC:"));
      Serial.print(idx);
      Serial.println(F(":255"));
    }
  }
  else if (strncmp(cmd, "NON:", 4) == 0 || strncmp(cmd, "NOF:", 4) == 0) {
    // Notes over the control link, so the web panel can play real hardware
    // without a MIDI keyboard: NON:<chan>:<note>:<vel>  NOF:<chan>:<note>
    bool on = (cmd[1] == 'O' && cmd[2] == 'N');
    char *p1 = cmd + 4;
    char *p2 = strchr(p1, ':');
    if (!p2) return;
    uint8_t chan = (uint8_t)atoi(p1);
    uint8_t note = (uint8_t)atoi(p2 + 1);
    uint8_t vel  = 100;
    char *p3 = strchr(p2 + 1, ':');
    if (p3) vel = (uint8_t)atoi(p3 + 1);
    if (on) noteOn(chan & 0x0F, note, vel);
    else    noteOff(chan & 0x0F, note, 0);
  }
  else if (strcmp(cmd, "CCMAP") == 0) {
    Serial.print(F("CCMAP:"));
    for (uint8_t i = 0; i < NUM_PARAMS; i++) {
      Serial.print(ccMap[i]);
      if (i < NUM_PARAMS - 1) Serial.print(',');
    }
    Serial.println();
  }
  else if (strcmp(cmd, "DIAG") == 0) {
    // Voice map: index:chip/what/stage/age-in-ticks. This is what to read
    // when notes choke -- it shows crowding and which chip drums landed on.
    // Free RAM first: now, and the worst it has ever been.
    Serial.print(F("RAM:"));
    Serial.print(freeRamNow());
    Serial.print(':');
    Serial.println(freeRamLow());

    Serial.print(F("DIAG "));
    for (uint8_t i = 0; i < MAX_VOICES; i++) {
      uint8_t idx = m_playing[i];
      Serial.print(i);
      Serial.print(F(":c"));
      Serial.print(i % 3);
      Serial.print('/');
      if (idx == NO_NOTE)        Serial.print(F("free"));
      else if (idx == PERC_NOTE) Serial.print(F("perc"));
      else { Serial.print('n'); Serial.print(MIDI_MIN + idx); }
      Serial.print('/');
      Serial.print((char)voices[i].m_adsr);
      Serial.print('/');
      Serial.print(voices[i].m_age);
      Serial.print(' ');
    }
    Serial.println();
  }
  else if (strcmp(cmd, "DUMP") == 0) {
    sendLayout();
    sendPreset();
    handleCommand((char *)"CCMAP");
  }
  else if (strncmp(cmd, "LOAD:", 5) == 0) {
    char *p = cmd + 5;
    uint8_t i = 0;
    while (*p && i < NUM_PARAMS) {
      setParam(i++, atoi(p));
      p = strchr(p, ',');
      if (!p) break;
      p++;
    }
    recalcDerived();
    if (i < NUM_PARAMS) {
      // Short preset: say so rather than leaving the tail at old values.
      Serial.print(F("ERR:SHORT "));
      Serial.print(i);
      Serial.print('/');
      Serial.println(NUM_PARAMS);
    }
    sendPreset();
  }
  else if (strcmp(cmd, "SAVE") == 0) {
    saveParamsToEEPROM();
    Serial.println(F("SAVED:1"));
  }
  else if (strcmp(cmd, "DEFAULTS") == 0) {
    loadDefaults();
    loadDefaultCcMap();
    recalcDerived();
    sendPreset();
  }
  // anything else: ignore silently
}

// Sized FROM NUM_PARAMS so it can never fall behind the parameter set:
// a LOAD: line is "LOAD:" + up to 3 digits and a comma per parameter.
// This was a fixed 96 bytes, which silently truncated a 34-parameter
// LOAD at around parameter 22 -- presets appeared to apply but everything
// past that kept its old value, with no error anywhere.
#define CMD_BUF_SIZE (NUM_PARAMS * 4 + 16)
static char     cmdBuf[CMD_BUF_SIZE];
static uint16_t cmdLen = 0;
static bool     cmdOverflow = false;

static void pollSerialControl() {
  while (Serial.available()) {
    char c = Serial.read();
    if (c == '\n' || c == '\r') {
      if (cmdOverflow) {
        // Never act on a truncated command -- a half-parsed LOAD would
        // apply some parameters and silently drop the rest.
        Serial.println(F("ERR:LONG"));
        cmdOverflow = false;
        cmdLen = 0;
      }
      else if (cmdLen > 0) {
        cmdBuf[cmdLen] = '\0';
        handleCommand(cmdBuf);
        cmdLen = 0;
      }
    }
    else if (cmdLen < CMD_BUF_SIZE - 1) {
      cmdBuf[cmdLen++] = c;
    }
    else {
      cmdOverflow = true;   // line too long: report it, don't half-apply it
    }
  }
}

static void update100Hz() {
  // Advance the LFOs once per tick (shared across voices).
  int8_t vibSample = 0;
  if (params[P_VIB_ENABLE]) {
    vibPhase += vibPhaseStep;
    vibSample = (int8_t)pgm_read_byte(&lfoSine[vibPhase >> 3]);
  }
  uint8_t tremCut = 0;
  if (params[P_TREM_ENABLE]) {
    tremPhase += tremPhaseStep;
    int s = (int8_t)pgm_read_byte(&lfoSine[tremPhase >> 3]);
    tremCut = (uint8_t)(((s + 127) * params[P_TREM_DEPTH]) >> 8); // 0..depth
  }

  // Flam: fire the pending repeat when its delay runs out.
  if (flamTicks > 0) {
    if (--flamTicks == 0) {
      flamFiring = true;
      startPercussion(flamNote);
      flamFiring = false;
    }
  }

  // Roll: re-strike the envelope of any drum still ringing. Writing the
  // shape register restarts the AY envelope from the top, which is the
  // whole trick -- at low rates it reads as a flam, at high rates a buzz
  // roll. Only percussion is envelope-driven, so nothing else is touched.
  if (params[P_DRUM_ROLL] > 0) {
    uint8_t every = pgm_read_byte(&RATE_EVERY[params[P_DRUM_ROLL]]);
    if (every == 0) every = 1;
    for (uint8_t i = 0; i < MAX_VOICES; i++) {
      if (m_playing[i] != PERC_NOTE || !voices[i].isPlaying()) continue;
      if (voices[i].m_age == 0 || (voices[i].m_age % every) != 0) continue;
      voices[i].m_ampl = Voice::AMPL_MAX;          // restart the cut-off timer
      writeReg(i % 3, PSGRegs::ENVSHAPE, (uint8_t)voices[i].m_shape);
    }
  }

  // Warp Motion: sweep the warp Rate on its own. The movement between
  // settings is usually more interesting than any fixed setting, so this
  // makes that movement continuous without a hand on the fader.
  if (params[P_WARP_MODE] != 0 && params[P_WARP_MOTION] > 0) {
    warpMotionPhase += (uint16_t)params[P_WARP_MOTION] * WARP_MOTION_SCALE;
    int8_t m = (int8_t)pgm_read_byte(&lfoSine[(warpMotionPhase >> 11) & 31]);
    int r = (int)params[P_WARP_RATE] + (((int)m * (int)params[P_WARP_RATE]) / 160);
    if (r < 1) r = 1;
    if (r > 120) r = 120;
    warpIntervalUs = 30000UL / (uint32_t)r;
    if (warpIntervalUs < 250UL) warpIntervalUs = 250UL;
  }

  // Arpeggio steps on a divided-down count of this 100Hz tick.
  if (params[P_ARP_MODE] > 0) {
    uint8_t ticksPerStep = 100 / params[P_ARP_RATE];
    if (ticksPerStep == 0) ticksPerStep = 1;
    if (++arpTickCount >= ticksPerStep) {
      arpTickCount = 0;
      if (++arpStep > 2) arpStep = 0;
    }
  } else {
    arpStep = 0;
    arpTickCount = 0;
  }

  for (ushort i = 0; i < MAX_VOICES; i++) {
    voices[i].update100Hz();

    // Master drum level. Percussion normally runs on the chip's hardware
    // envelope (M bit set), whose full scale cannot be scaled -- so to get a
    // level at all the voice is moved onto its own software amplitude.
    // Slightly softer transient, which is why 15 leaves it alone entirely.
    if ((params[P_MIX_DRUM] < 15 || voices[i].m_softEnv)
        && m_playing[i] == PERC_NOTE && voices[i].isPlaying()) {
      uint8_t dcut = pgm_read_byte(&MIX_ATTEN[params[P_MIX_DRUM] & 15]);
      int da = (voices[i].m_ampl >> 6) - (int)dcut;
      if (da < 0) da = 0;
      if (da < 0) da = 0;
      if (da > 15) da = 15;
      psg.regs[i % 3][PSGRegs::TONEAAMPL + (i / 3)] = (uint8_t)da;  // M clear
    }

    if (m_playing[i] == PERC_NOTE && ! (voices[i].isPlaying())) {
      m_playing[i] = NO_NOTE;
      restartANote();
    }

    // Final tone/amplitude write for sounding melodic voices, with all
    // modifiers applied. voices[i].update100Hz() already wrote its plain
    // value into the register cache; writing again just replaces it in RAM
    // before the hardware flush, and setTone() is idempotent on the mixer
    // bits, so this layering is safe.
    if (m_playing[i] != PERC_NOTE && voices[i].isPlaying()) {

      // Retrigger: re-strike the envelope while the note is still held.
      if (params[P_RETRIG_RATE] > 0 && voices[i].m_age > 0) {
        uint8_t every = pgm_read_byte(&RATE_EVERY[params[P_RETRIG_RATE]]);
        if (every == 0) every = 1;
        if (voices[i].m_age % every == 0) {
          voices[i].m_ampl = voices[i].m_vel;
          voices[i].m_adsr = 'D';
        }
      }

      ushort p = voices[i].m_pitch;

      // Arpeggio: re-pitch the voice by whole semitones from the note
      // table. This replaces the glide-slewed pitch rather than nudging it,
      // so arpeggio and glide don't fight over the same divisor.
      if (params[P_ARP_MODE] > 0) {
        int8_t off = (int8_t)pgm_read_byte(&arpTable[params[P_ARP_MODE] - 1][arpStep]);
        int idx = (int)voices[i].m_noteIdx + off;
        if (idx < 0) idx = 0;
        if (idx >= (int)N_NOTES) idx = (int)N_NOTES - 1;
        p = pgm_read_word(&note_table[idx]);
      }

      // Auto sweep: NES-style automatic pitch slide, accumulating with note
      // age. Positive raises pitch, which means SHRINKING the divisor.
      int8_t sweep = (int8_t)((int)params[P_SWEEP_AMOUNT] - 32);
      if (sweep != 0) {
        int32_t sp = (int32_t)p - (((int32_t)sweep * voices[i].m_age) >> 3);
        if (sp < 1) sp = 1;
        if (sp > 4095) sp = 4095;
        p = (ushort)sp;
      }

      // Vibrato with delayed onset: waits P_VIB_DELAY ticks (10ms each)
      // after note start, then fades the depth in over ~250ms.
      if (params[P_VIB_ENABLE] && params[P_VIB_DEPTH] > 0) {
        uint16_t delayTicks = params[P_VIB_DELAY];
        if (voices[i].m_age > delayTicks) {
          uint16_t ramp = voices[i].m_age - delayTicks;
          uint8_t depth = params[P_VIB_DEPTH];
          if (ramp < 25) depth = (uint8_t)(((uint16_t)depth * ramp) / 25);
          int32_t off = ((int32_t)p * vibSample * depth) >> 14;
          int32_t wp = (int32_t)p + off;
          if (wp < 1) wp = 1;
          if (wp > 4095) wp = 4095;
          p = (ushort)wp;
        }
      }

      int a = (voices[i].m_ampl >> 6) - tremCut;
      if (a < 0) a = 0;
      if (params[P_MIX_TONE] < 15) {
        uint8_t cut = pgm_read_byte(&MIX_ATTEN[params[P_MIX_TONE] & 15]);
        a = (a > (int)cut) ? a - (int)cut : 0;
      }

      // Noise blend: mixes the AY noise generator into the voice. NOTE:
      // the noise period register is per-chip and shared with percussion
      // -- a drum and a noise-blended voice on the same chip fight over
      // it, last writer wins. Chip-level quirk, documented behaviour.
      if (i == waveVoice) {
        // The wavetable ISR writes this channel's amplitude sixteen thousand
        // times a second. Writing it from here too put a step in the waveform
        // on every tick, a hundred times a second. The ADSR still runs above
        // -- it is what ends the note -- but only the pitch is written.
        psg.setTonePitchOnly(i, p);
      } else if (params[P_NOISE_ENABLE]) {
        psg.setToneAndNoise(i, p, params[P_NOISE_PERIOD], a);
      } else {
        psg.setTone(i, p, a);
      }
    }
  }

  applyBuzzyBass();
  applyWavetable();
}

// Main code ----------------------------------------------

static unsigned long lastUpdate = 0;
static unsigned long lastWarpUs = 0;

void setup() {
  // Paint the free RAM before anything has had a chance to use much stack,
  // so the high-water reading covers the whole run.
  paintFreeRam();
  waveTimerInit();

  // Hold in reset while we set up the reset
  pinMode(nRESET, OUTPUT);
  digitalWrite(nRESET, LOW);

  pinMode(clkOUT, OUTPUT);
  digitalWrite(clkOUT, LOW);
  clockSetup();

  pinMode(BC2_A, OUTPUT);
  digitalWrite(BC2_A, LOW); // BC2 low
  pinMode(BDIR_A, OUTPUT);
  digitalWrite(BDIR_A, LOW); // BDIR low

  pinMode(BC2_B, OUTPUT);
  digitalWrite(BC2_B, LOW); // BC2 low
  pinMode(BDIR_B, OUTPUT);
  digitalWrite(BDIR_B, LOW); // BDIR low

  pinMode(BC2_C, OUTPUT);
  digitalWrite(BC2_C, LOW); // BC2 low
  pinMode(BDIR_C, OUTPUT);
  digitalWrite(BDIR_C, LOW); // BDIR low

  for (ushort i = 0; i < 8; i++) {
    uint8_t pin = pgm_read_byte(&dbus[i]);
    pinMode(pin, OUTPUT);
    digitalWrite(pin, LOW); // Set bus low
  }

  // Resolve dbus/BDIR/BC2 pins to their AVR port registers + bitmasks now
  // that they're all configured as OUTPUT. Must happen before any
  // writeReg()/setData() call (i.e. before psg.init() below).
  initBusPins();

  delay(100);
  digitalWrite(nRESET, HIGH); // Release Reset
  delay(10);

  lastUpdate = millis();
  
  psg.init();
  for (ushort i = 0; i < MAX_VOICES; i++) {
    voices[i].init(i);
  }
  synth_init();

  // Parameter bank: restore the last EEPROM-saved bank if it matches the
  // current generated layout, otherwise start from the generated defaults.
  loadDefaultCcMap();
  if (!loadParamsFromEEPROM()) {
    loadDefaults();
  }
  recalcDerived();

  // Serial (USB-CDC) is needed unconditionally for the parameter protocol,
  // not just for #ifdef DEBUG logging.
  Serial.begin(115200);
  sendLayout();
  sendPreset(); // let an already-connected panel resync after a board reset

#ifdef SERIALMIDI
  // Initiate MIDI communications, listen to all channels
  MIDI.begin(MIDI_CHANNEL_OMNI);
#endif
}

// Silences everything and returns the synth to a known state WITHOUT
// rebooting the MCU. The V2.2 firmware called resetFunc() here, which jumps
// to address 0 and takes USB down with it -- if a DAW or controller sends
// All Notes Off periodically, the unit drops off the bus mid-session and
// uploads fail. This does the musical part of a reset and leaves USB alone.
static void softReset() {
  for (ushort i = 0; i < MAX_VOICES; i++) {
    voices[i].kill();
  }
  synth_init();

  g_buzzChip = -1;
  g_buzzSub  = -1;
  arpStep = 0;
  arpTickCount = 0;

  psg.init();                       // re-initialise all three chips
  psg.invalidate();
}

void handleMidiMessage(midiEventPacket_t &rx) {
  if (rx.header==0x9) {// Note on
    noteOn(rx.byte1 & 0xF, rx.byte2, rx.byte3);
  }
  else if (rx.header==0x8) {// Note off
    noteOff(rx.byte1 & 0xF, rx.byte2, rx.byte3);
  }
  else if (rx.header==0xB) {// Control Change
    if (rx.byte2 == 0x78 || rx.byte2 == 0x79 || rx.byte2 == 0x7B) {// AllSoundOff, ResetAllControllers, or AllNotesOff
      softReset();
    }
    else {
      handleControlChange(rx.byte2, rx.byte3);
    }
  }
}

void loop() {
  midiEventPacket_t rx;

  pollSerialControl(); // BUZZ/VIB parameter commands over USB-CDC serial

#ifdef USBMIDI
  rx = MidiUSB.read();

#ifdef DEBUG
  //MIDI debugging
  if (rx.header != 0) {
    Serial.print("Received USB: ");
    Serial.print(rx.header, HEX);
    Serial.print("-");
    Serial.print(rx.byte1, HEX);
    Serial.print("-");
    Serial.print(rx.byte2, HEX);
    Serial.print("-");
    Serial.println(rx.byte3, HEX);
  }
#endif

  handleMidiMessage(rx);
#endif

#ifdef SERIALMIDI
  //Check for serial MIDI messages
  //MIDI.read();
  while (MIDI.read()) {
    // Create midiEventPacket_t
    rx = 
      {
        byte(MIDI.getType() >>4), 
        byte(MIDI.getType() | ((MIDI.getChannel()-1) & 0x0f)), /* getChannel() returns values from 1 to 16 */
        MIDI.getData1(), 
        MIDI.getData2()
      };

#ifdef DEBUG
    //MIDI debugging
    if (rx.header != 0) {
      Serial.print("Received MIDI: ");
      Serial.print(rx.header, HEX);
      Serial.print("-");
      Serial.print(rx.byte1, HEX);
      Serial.print("-");
      Serial.print(rx.byte2, HEX);
      Serial.print("-");
      Serial.println(rx.byte3, HEX);
    }
#endif

    handleMidiMessage(rx);
  }
#endif

  unsigned long now = millis();
  // Clock Warp drags the MCU's own tick along with the chip clock. Without
  // this only half of each sound moved: tone periods, noise colour and the
  // hardware envelope are chip-side and slow with the clock, but amplitude
  // decay, drum length, rolls and every LFO are counted here in milliseconds
  // and carried on regardless. A drum is mostly the MCU half, which is why
  // the effect barely showed on the kit. Scaling the tick makes it genuine
  // vari-speed: at the deepest sag everything runs near a third speed.
  uint8_t tickMs = 10;
  if (params[P_WARP_MODE] == 10) {
    uint16_t div = OCR1AL ? OCR1AL : DIVISOR;
    uint16_t t = (uint16_t)((10u * div + (DIVISOR / 2)) / DIVISOR);
    if (t < 3) t = 3;
    if (t > 40) t = 40;
    tickMs = (uint8_t)t;
  }
  if ((now - lastUpdate) >= tickMs) {
    update100Hz();
    lastUpdate += tickMs; // was += 5 against a >10ms check, causing the
                          // envelope/perc update rate to drift ~2x fast
                          // whenever the loop fell behind and had to catch up
  }

  // Warp Zone runs far faster than the 100Hz voice tick -- up to ~4kHz --
  // so it gets its own micros() timer. Unsigned subtraction handles the
  // ~70 minute micros() rollover correctly.
  if (params[P_WARP_MODE] != 0 || params[P_MIX_NOISE] < 15) {
    unsigned long nowUs = micros();

    // The noise gate keeps its own fixed 4kHz clock: tying it to the warp
    // rate would turn a slow warp setting into audible noise chopping.
    if (params[P_MIX_NOISE] < 15 &&
        (unsigned long)(nowUs - lastNoiseUs) >= NOISE_GATE_US) {
      lastNoiseUs = nowUs;
      noiseGateTick();
    }

    if (params[P_WARP_MODE] != 0 &&
        (unsigned long)(nowUs - lastWarpUs) >= warpIntervalUs) {
      lastWarpUs = nowUs;
      warpTick();
    }
  }

  psg.updateAll();

}
