/*
 * The bulk of this firmware comes from: https://dogemicrosystems.ca/wiki/Dual_AY-3-8910_MIDI_module
 * 
 * Firmware Version 2.2 for the 8-Bit 8asterd by Semiotic Sounds
 * 
 * Added:
 * Drum Polyphony
 * Slow attack evelopes on channels 3 and 4
 * Altered drum sounds (808 bass and clave)
 * Arduino Reset function on MIDI KillAll message
 * Better voice distribution methodology
 */

void(* resetFunc) (void) = 0;//declare reset function at address 0

// Uncomment to enable 5-pin DIN serial midi
#define SERIALMIDI

// Uncomment to enable USB midi
#define USBMIDI

// Uncomment to enable debugging output over USB serial
#define DEBUG

#include <avr/io.h>
#include <string.h>
#include <stdlib.h>

#ifdef USBMIDI
#include "MIDIUSB.h"
#endif

// We borrow one struct from MIDIUSB for traditional serial midi, so define it if were not using USBMIDI
#ifndef MIDIUSB_h
typedef struct
{
  uint8_t header;
  uint8_t byte1;
  uint8_t byte2;
  uint8_t byte3;
} midiEventPacket_t;
#endif

#ifdef SERIALMIDI
#include <MIDI.h>
MIDI_CREATE_INSTANCE(HardwareSerial, Serial1, MIDI);//Serial1 on pro micro
#endif

typedef unsigned short int ushort;

typedef unsigned char note_t;
#define NOTE_OFF 0

typedef unsigned char midictrl_t;

// --- Fast direct-port I/O -------------------------------------------------
// KEEP THESE STRUCTS ABOVE EVERY FUNCTION DEFINITION IN THIS FILE. The
// Arduino .ino preprocessor auto-generates function prototypes and inserts
// them immediately before the first function definition; pinHigh()/pinLow()
// take a BusPin&, so if BusPin is declared after that point the generated
// prototype references an undeclared type and the build fails with
// "'BusPin' does not name a type".
//
// digitalWrite() costs ~50+ cycles on AVR (pin validation, PWM-timer
// disable check, interrupt mask save/restore). Every register write here
// needs 8 data-bit writes plus several BDIR/BC2 toggles, and this happens
// constantly on the voice/envelope hot path while MIDI also needs servicing.
// We resolve each pin to its AVR PORT register + bitmask once at startup
// (via the standard Arduino pin-mapping macros, so this stays portable if
// pins are reassigned) and then do a 1-2 instruction read-modify-write
// instead. This is roughly an order of magnitude faster per pin toggle.

struct BusPin {
  volatile uint8_t *port;
  uint8_t mask;
};

static BusPin dbusPins[8];

struct ChipCtl {
  BusPin bdir;
  BusPin bc2;
};

static ChipCtl chipCtl[3]; // 0 = chip A, 1 = chip B, 2 = chip C

// Voice/FX parameter structs live up here for the same reason as BusPin
// above: any top-level function taking one (applyDrumMods) gets an
// auto-generated prototype inserted before the first function definition.

struct FXParams {
  ushort noisefreq;
  ushort tonefreq;
  ushort envdecay;
  ushort freqdecay;
  ushort timer;
  ushort shape;
};

struct ToneParams {
  ushort attack;
  ushort decay;
  ushort sustain; // Values 0..32
  ushort rel;
};

// --- Parameter bank -------------------------------------------------------
// parameters.h is GENERATED by generate.py (indices, ranges, defaults, and a
// layout-version byte). The bank is a flat uint8_t array in index order --
// the same array the web panel edits over serial and that presets are made
// of. Edit generate.py, re-run it, reflash; never edit parameters.h by hand.
#include "parameters.h"
#include <EEPROM.h>

static uint8_t params[NUM_PARAMS];

// AY envelope shapes that loop continuously (P_BUZZ_SHAPE is an index here):
static const uint8_t buzzShapes[4] PROGMEM = { 8, 10, 12, 14 };

static void loadDefaults() {
  for (uint8_t i = 0; i < NUM_PARAMS; i++) {
    params[i] = pgm_read_byte(&PARAM_DEFAULT[i]);
  }
}

static void setParam(uint8_t idx, int val) {
  if (idx >= NUM_PARAMS) return;
  int lo = pgm_read_byte(&PARAM_MIN[idx]);
  int hi = pgm_read_byte(&PARAM_MAX[idx]);
  if (val < lo) val = lo;
  if (val > hi) val = hi;
  params[idx] = (uint8_t)val;
}

// EEPROM layout: '8' 'B' <layout version> <param count> <params...>
// The layout version is derived from the parameter definition by
// generate.py, so a saved bank from an older definition is simply ignored.
static void saveParamsToEEPROM() {
  EEPROM.update(0, '8');
  EEPROM.update(1, 'B');
  EEPROM.update(2, PARAM_LAYOUT_VERSION);
  EEPROM.update(3, NUM_PARAMS);
  for (uint8_t i = 0; i < NUM_PARAMS; i++) {
    EEPROM.update(4 + i, params[i]);
  }
}

static bool loadParamsFromEEPROM() {
  if (EEPROM.read(0) != '8' || EEPROM.read(1) != 'B' ||
      EEPROM.read(2) != PARAM_LAYOUT_VERSION || EEPROM.read(3) != NUM_PARAMS) {
    return false;
  }
  for (uint8_t i = 0; i < NUM_PARAMS; i++) {
    setParam(i, EEPROM.read(4 + i)); // clamp on the way in
  }
  return true;
}

// Pin driver ---------------------------------------------

// Pin numbers all fit in a byte; PROGMEM keeps the table out of RAM.
static const uint8_t dbus[8] PROGMEM = { 2, 3, 4, 5, 6, 7, 8, 10 };

static const ushort
  BC2_A = 14,
  BDIR_A = 16,
  BC2_B = A1,
  BDIR_B = A0,
  BC2_C = A3,
  BDIR_C = A2,
  nRESET = 15,
  clkOUT = 9;

static const ushort DIVISOR = 7; // Set for 1MHz clock


static void clockSetup() {
   // Timer 1 setup for Mega32U4 devices
   //
   // Use CTC mode: WGM13..0 = 0100
   // Toggle OC1A on Compare Match: COM1A1..0 = 01
   // Use ClkIO with no prescaling: CS12..0 = 001
   // Interrupts off: TIMSK0 = 0
   // OCR0A = interval value
   
   TCCR1A = (1 << COM1A0);
   TCCR1B = (1 << WGM12) | (1 << CS10);
   TCCR1C = 0;
   TIMSK1 = 0;
   OCR1AH = 0;
   OCR1AL = DIVISOR; // NB write high byte first
}


static inline void pinHigh(const BusPin &p) { *p.port |= p.mask; }
static inline void pinLow(const BusPin &p)  { *p.port &= ~p.mask; }

static void setData(unsigned char db) {
  unsigned char bit = 1;
  for (ushort i = 0; i < 8; i++) {
    if (db & bit) pinHigh(dbusPins[i]);
    else pinLow(dbusPins[i]);
    bit <<= 1;
  }
}

static void initBusPins() {
  for (uint8_t i = 0; i < 8; i++) {
    uint8_t pin = pgm_read_byte(&dbus[i]);
    dbusPins[i].port = portOutputRegister(digitalPinToPort(pin));
    dbusPins[i].mask = digitalPinToBitMask(pin);
  }

  const ushort bdirPins[3] = { BDIR_A, BDIR_B, BDIR_C };
  const ushort bc2Pins[3]  = { BC2_A,  BC2_B,  BC2_C  };

  for (uint8_t c = 0; c < 3; c++) {
    chipCtl[c].bdir.port = portOutputRegister(digitalPinToPort(bdirPins[c]));
    chipCtl[c].bdir.mask = digitalPinToBitMask(bdirPins[c]);
    chipCtl[c].bc2.port  = portOutputRegister(digitalPinToPort(bc2Pins[c]));
    chipCtl[c].bc2.mask  = digitalPinToBitMask(bc2Pins[c]);
  }
}

static void writeReg(uint8_t chip, unsigned char reg, unsigned char db) {
  // Same BC1-kept-low NACT/BAR/IAB/DWS sequencing as the original, just
  // routed through direct port writes instead of digitalWrite().
  ChipCtl &c = chipCtl[chip];

  // Inactive (BDIR BC2 BC1 0 0 0)
  pinLow(c.bdir);
  pinLow(c.bc2);

  // Set register address
  setData(reg);

  // BAR (Latch) (BDIR BC2 BC1 1 0 0)
  pinHigh(c.bdir);

  // Inactive (BDIR BC2 BC1 0 0 0)
  pinLow(c.bdir);

  // Set register contents
  setData(db);

  // Write (BDIR BC2 BC1 1 1 0)
  pinHigh(c.bc2);
  pinHigh(c.bdir);

  // Inactive (BDIR BC2 BC1 0 0 0)
  pinLow(c.bc2);
  pinLow(c.bdir);
}

// AY-3-8910 driver ---------------------------------------

class PSGRegs {
public:
  enum {
    TONEALOW = 0,
    TONEAHIGH,
    TONEBLOW,
    TONEBHIGH,
    TONECLOW,
    TONECHIGH,
    NOISEGEN,
    MIXER,
    TONEAAMPL,
    TONEBAMPL,
    TONECAMPL,
    ENVLOW,
    ENVHIGH,
    ENVSHAPE,
    IOA,
    IOB
  };

  //MIXER
//   0 = A+B+C+Noise            [0]
// 248 = A+B+C                  [1]
// 199 = Noise only on A+B+C    [2]
// 254 = A Only                 [3]
// 253 = B only                 [4]
// 251 = C only                 [5]
// 252 = A+B                    [6]
// 249 = B+C                    [7]
// 246 = A+Noise                [8]
// 237 = B+Noise                [9]
// 219 = C+Noise                [10]
// 238 = A+Noise on B           [11]
// 221 = B+Noise on C           [12]
// 243 = C+Noise on A           [13]
// 247 = Noise only on A        [14]
// 239 = Noise only on B        [15]
// 223 = Noise only on C        [16]
  
  // Chip-indexed register storage: regs[0]=chip A, regs[1]=chip B, regs[2]=chip C.
  // The original had three full copies of these arrays (regs_A/B/C,
  // lastregs_A/B/C) plus three near-identical writeReg_A/B/C and three
  // near-identical update_A/B/C. Every voice channel 0..8 maps onto one of
  // the three chips via chip = ch % 3 and a sub-channel sub = ch / 3 (0,3,6
  // -> chip A; 1,4,7 -> chip B; 2,5,8 -> chip C, matching the original
  // mapping exactly). That collapses what used to be three copy-pasted
  // if/else-if chains per method into one formula, and incidentally fixes a
  // real bug in the original setPercOff(): its chip-A branch read
  // regs_C[MIXER] and its chip-C branch read regs_A[MIXER] instead of their
  // own chip's mixer register.
  unsigned char regs[3][16];
  unsigned char lastregs[3][16];

  void init() {
    for (uint8_t c = 0; c < 3; c++) {
      for (int i = 0; i < 16; i++) {
        regs[c][i] = lastregs[c][i] = 0xFF;
        writeReg(c, i, regs[c][i]);
      }
    }
  }

  void update(uint8_t chip) {
    unsigned char *r = regs[chip];
    unsigned char *lr = lastregs[chip];
    for (int i = 0; i < 16; i++) {
      if (r[i] != lr[i]) {
        writeReg(chip, i, r[i]);
        lr[i] = r[i];
      }
    }
  }

  void updateAll() {
    update(0);
    update(1);
    update(2);
  }

  void setTone(ushort ch, ushort divisor, ushort ampl) {
    uint8_t chip = ch % 3;
    uint8_t sub  = ch / 3;
    unsigned char *r = regs[chip];

    r[TONEALOW  + (sub<<1)] = (divisor & 0xFF);
    r[TONEAHIGH + (sub<<1)] = (divisor >> 8);
    r[TONEAAMPL + sub] = ampl;

    ushort mask = (8+1) << sub;
    r[MIXER] = (r[MIXER] | mask) ^ (1 << sub);
  }

  void setToneAndNoise(ushort ch, ushort divisor, ushort noisefreq, ushort ampl) {
    uint8_t chip = ch % 3;
    uint8_t sub  = ch / 3;
    unsigned char *r = regs[chip];

    r[TONEALOW  + (sub<<1)] = (divisor & 0xFF);
    r[TONEAHIGH + (sub<<1)] = (divisor >> 8);
    r[NOISEGEN] = noisefreq;
    r[TONEAAMPL + sub] = ampl;

    ushort mask = (8+1) << sub;
    ushort bits = (noisefreq < 16 ? 8 : 0) + (divisor > 0 ? 1 : 0);
    r[MIXER] = (r[MIXER] | mask) ^ (bits << sub);
  }

  void setEnvelope(ushort ch, ushort divisor, ushort shape) {
    unsigned char *r = regs[ch % 3];
    r[ENVLOW]  = (divisor & 0xFF);
    r[ENVHIGH] = (divisor >> 8);
    r[ENVSHAPE] = shape;
  }

  void setPercOff(ushort ch) {
    uint8_t chip = ch % 3;
    uint8_t sub  = ch / 3;
    unsigned char *r = regs[chip];

    ushort mask = (8+1) << sub;
    r[MIXER] |= mask;
    r[TONEAAMPL + sub] = 0;
    if (r[ENVSHAPE] != 0) {
      r[ENVSHAPE] = 0;
      update(chip); // Force flush
    }
  }

  // setOff() was an exact duplicate of setPercOff() in the original.
  void setOff(ushort ch) {
    setPercOff(ch);
  }

  // --- Buzzy bass -----------------------------------------------------
  // The AY's envelope generator is one-per-chip, shared by all three of
  // that chip's channels, and a channel's volume is driven by it whenever
  // bit 4 (0x10, the "M" bit) of its amplitude register is set -- in which
  // case the lower 4 (fixed-level) bits are ignored by the chip. ratio
  // scales the channel's tone divisor to get the envelope-period divisor;
  // there's no clean closed-form for "in tune", so this is meant to be
  // tuned by ear via the ratio control rather than computed exactly.
  void applyBuzz(uint8_t chip, uint8_t sub, ushort toneDivisor, uint8_t ratio, uint8_t shape) {
    unsigned char *r = regs[chip];
    uint16_t envDivisor = (uint16_t)toneDivisor * ratio;
    if (envDivisor < 1) envDivisor = 1;
    r[ENVLOW]  = envDivisor & 0xFF;
    r[ENVHIGH] = envDivisor >> 8;
    r[ENVSHAPE] = shape;
    r[TONEAAMPL + sub] = 0x10; // M=1: volume follows the envelope generator
  }

  void clearBuzz(uint8_t chip, uint8_t sub) {
    // Just drop the envelope-mode bit; the very next normal tone/amplitude
    // write for this voice (next 100Hz tick, at most 10ms away) restores
    // the correct fixed-level volume.
    regs[chip][TONEAAMPL + sub] &= ~0x10;
  }
};

static PSGRegs psg;

// Voice generation ---------------------------------------

static const ushort
  MIDI_MIN = 24,
  MIDI_MAX = 96,
  N_NOTES = (MIDI_MAX+1-MIDI_MIN);

static const ushort note_table[N_NOTES] PROGMEM = {
   1911, // MIDI 24, 32.70 Hz
   1804, // MIDI 25, 34.65 Hz
   1703, // MIDI 26, 36.71 Hz
   1607, // MIDI 27, 38.89 Hz
   1517, // MIDI 28, 41.20 Hz
   1432, // MIDI 29, 43.65 Hz
   1351, // MIDI 30, 46.25 Hz
   1276, // MIDI 31, 49.00 Hz
   1204, // MIDI 32, 51.91 Hz
   1136, // MIDI 33, 55.00 Hz
   1073, // MIDI 34, 58.27 Hz
   1012, // MIDI 35, 61.74 Hz
   956, // MIDI 36, 65.41 Hz
   902, // MIDI 37, 69.30 Hz
   851, // MIDI 38, 73.42 Hz
   804, // MIDI 39, 77.78 Hz
   758, // MIDI 40, 82.41 Hz
   716, // MIDI 41, 87.31 Hz
   676, // MIDI 42, 92.50 Hz
   638, // MIDI 43, 98.00 Hz
   602, // MIDI 44, 103.83 Hz
   568, // MIDI 45, 110.00 Hz
   536, // MIDI 46, 116.54 Hz
   506, // MIDI 47, 123.47 Hz
   478, // MIDI 48, 130.81 Hz
   451, // MIDI 49, 138.59 Hz
   426, // MIDI 50, 146.83 Hz
   402, // MIDI 51, 155.56 Hz
   379, // MIDI 52, 164.81 Hz
   358, // MIDI 53, 174.61 Hz
   338, // MIDI 54, 185.00 Hz
   319, // MIDI 55, 196.00 Hz
   301, // MIDI 56, 207.65 Hz
   284, // MIDI 57, 220.00 Hz
   268, // MIDI 58, 233.08 Hz
   253, // MIDI 59, 246.94 Hz
   239, // MIDI 60, 261.63 Hz
   225, // MIDI 61, 277.18 Hz
   213, // MIDI 62, 293.66 Hz
   201, // MIDI 63, 311.13 Hz
   190, // MIDI 64, 329.63 Hz
   179, // MIDI 65, 349.23 Hz
   169, // MIDI 66, 369.99 Hz
   159, // MIDI 67, 392.00 Hz
   150, // MIDI 68, 415.30 Hz
   142, // MIDI 69, 440.00 Hz
   134, // MIDI 70, 466.16 Hz
   127, // MIDI 71, 493.88 Hz
   119, // MIDI 72, 523.25 Hz
   113, // MIDI 73, 554.37 Hz
   106, // MIDI 74, 587.33 Hz
   100, // MIDI 75, 622.25 Hz
   95, // MIDI 76, 659.26 Hz
   89, // MIDI 77, 698.46 Hz
   84, // MIDI 78, 739.99 Hz
   80, // MIDI 79, 783.99 Hz
   75, // MIDI 80, 830.61 Hz
   71, // MIDI 81, 880.00 Hz
   67, // MIDI 82, 932.33 Hz
   63, // MIDI 83, 987.77 Hz
   60, // MIDI 84, 1046.50 Hz
   56, // MIDI 85, 1108.73 Hz
   53, // MIDI 86, 1174.66 Hz
   50, // MIDI 87, 1244.51 Hz
   47, // MIDI 88, 1318.51 Hz
   45, // MIDI 89, 1396.91 Hz
   42, // MIDI 90, 1479.98 Hz
   40, // MIDI 91, 1567.98 Hz
   38, // MIDI 92, 1661.22 Hz
   36, // MIDI 93, 1760.00 Hz
   34, // MIDI 94, 1864.66 Hz
   32, // MIDI 95, 1975.53 Hz
   30, // MIDI 96, 2093.00 Hz
};

static const ushort MAX_TONES = 4;
static const ToneParams tones[MAX_TONES] PROGMEM = {
  { 1, 8, 32, 32 },
  { 1 , 8,  1,  32 },
  { 8, 1, 1, 32 },
  { 4, 1, 32, 1 }
};

// For glide: the divisor of the most recently started melodic note, so a
// new note can slide in from wherever the last one landed.
static ushort g_lastMelodicPitch = 0;

class Voice {
public:
  ushort m_chan;  // Index to psg channel 
  ushort m_pitch;   // current (glide-slewed) tone divisor
  ushort m_target;  // divisor of the note actually requested
  uint16_t m_age;   // ticks since note start (for delayed vibrato onset)
  int m_attack, m_ampl, m_ampl_top, m_decay, m_sustain, m_release, m_shape;
  static const int AMPL_MAX = 1023;
  ushort m_adsr;
  ushort m_vel;

  void init (ushort chan) {
    m_chan = chan;
    m_ampl = m_sustain = 0;
    m_target = 0;
    m_age = 0;
    kill();
  }
  
  void start(note_t note, midictrl_t vel, midictrl_t chan) {
    // Envelope source: either the original per-MIDI-channel presets, or the
    // global custom ADSR from the parameter bank.
    ToneParams tp;
    if (params[P_ENV_MODE] == 1) {
      tp.attack  = params[P_ENV_ATTACK];
      tp.decay   = params[P_ENV_DECAY];
      tp.sustain = params[P_ENV_SUSTAIN];
      tp.rel     = params[P_ENV_RELEASE];
    } else {
      memcpy_P(&tp, &tones[chan % MAX_TONES], sizeof(ToneParams));
    }

    if (params[P_VEL_SENSE] == 0) {
      vel = 127; // velocity response off: everything at full volume
    }

    // Transpose, clamped to the note table.
    int n = (int)note - MIDI_MIN + (int)params[P_TRANSPOSE] - 24;
    if (n < 0) n = 0;
    if (n >= (int)N_NOTES) n = (int)N_NOTES - 1;
    m_target = pgm_read_word(&note_table[n]);

    // Glide: start from wherever the previous note's pitch was and slew
    // toward the target in update100Hz(). 0 = jump straight there.
    if (params[P_GLIDE] > 0 && g_lastMelodicPitch > 0) {
      m_pitch = g_lastMelodicPitch;
    } else {
      m_pitch = m_target;
    }
    g_lastMelodicPitch = m_target;
    m_age = 0;

    m_vel = 768 + (vel << 1);
    m_attack = tp.attack;
    m_decay = tp.decay; 
    //m_decay = 0; 

        if (vel > 127) {
      m_ampl = AMPL_MAX;
      m_ampl_top = AMPL_MAX;
    }

    
     if (m_attack > 1) {
      m_adsr = 'A';
      //m_ampl = 768 + (vel << 1);
      m_ampl = 255 + (m_attack >> 1);
    }



    else {
      m_ampl = 768 + (vel << 1);
      m_adsr = 'D';
      }
    
    m_sustain = (m_ampl * tp.sustain) >> 5;
    
    m_release = tp.rel;
    
    
    //psg.setEnvelope(32, 11); 
    psg.setTone(m_chan, m_pitch, m_ampl >> 6);
  }

  struct FXParams m_fxp;
  
  void startFX(const struct FXParams &fxp) {
    m_fxp = fxp;
  
    if (m_ampl > 0) {
      psg.setPercOff(m_chan);
    }
    m_ampl = AMPL_MAX;
    //m_ampl = 255 + (m_vel << 1);
    m_adsr = 'X';
    m_decay = fxp.timer;
    m_shape = fxp.shape;
    //m_decay = 96;


// 9 = Just release             [0]
// 4 = Reverse Release          [1]
// 8 = Repeat Release           [2]
// 12 = Reverse Repeat Release  [3]
// 10 = Repeat Release Waves    [4]
// 14 = Reverse Repeat Waves    [5]
// 11 = Release and on          [6]


  // setEnvelope() derives the chip internally via ch % 3, so m_chan can be
  // passed straight through (no need to re-decode which chip it belongs to).
  psg.setEnvelope(m_chan, fxp.envdecay, m_shape);
#ifdef DEBUG
  Serial.print("CH: ");
  Serial.println(m_chan);
#endif
    psg.setToneAndNoise(m_chan, fxp.tonefreq, fxp.noisefreq, 30);
  }
  

  void stop() {
    if (m_adsr == 'X') {
      //psg.setPercOff(m_chan);
      return; // Will finish when ready...
    }
      
    if (m_ampl > 0) {
      m_adsr = 'R';
    }
    
    else {
      psg.setOff(m_chan);
      //psg.setPercOff(m_chan);
    }
  }
  
  void update100Hz() {
    if (m_age < 65000) m_age++;

    // Glide: slew m_pitch toward the requested note. Proportional step so
    // big jumps move fast at first; forced +/-1 floor so it always arrives.
    if (m_adsr != 'X' && m_pitch != m_target) {
      if (params[P_GLIDE] == 0) {
        m_pitch = m_target;
      } else {
        int diff = (int)m_target - (int)m_pitch;
        int step = ((int32_t)diff * (100 - params[P_GLIDE])) / 100;
        if (step == 0) step = (diff > 0) ? 1 : -1;
        m_pitch += step;
      }
    }

   if (m_ampl == 0) {
      return;
    }
    
    switch(m_adsr) {
//
      case 'A':
        if (m_ampl < m_vel) {
         
        m_ampl += (m_attack << 1);
        //m_adsr = 'A';
        }
//
        
        
        if (m_ampl >= m_vel) {
          m_adsr = 'D';
        };
       
        
        break;
        
      case 'D':
        
        if (m_ampl <= m_sustain) {
          m_adsr = 'S';
          m_ampl = m_sustain;
        }
        
        m_ampl -= m_decay;
        
        break;

      case 'S':
        break;

      case 'R':
        if ( m_ampl < m_release ) {
          m_ampl = 0;
        }
        else {
          m_ampl -= m_release;
        }
        break;

      case 'X':
        // FX is playing.         
        if (m_fxp.freqdecay > 0) { 
          m_fxp.tonefreq += m_fxp.freqdecay;
          //psg.setEnvelope(m_fxp.envdecay, 9); 
          psg.setToneAndNoise(m_chan, m_fxp.tonefreq, m_fxp.noisefreq, 30);
        }
        
        m_ampl -= m_decay;
        
        if (m_ampl < 0) {
   
          //psg.setOff(m_chan);
          psg.setPercOff(m_chan); 
          m_ampl = 0;
        }
        return;
        
      default:
        break;
    }  

    if (m_ampl > 0) {          
      psg.setTone(m_chan, m_pitch, m_ampl >> 6);
    }
    else {
      psg.setOff(m_chan);    
      psg.setPercOff(m_chan);  
    }
  }
  
  bool isPlaying() {
    return (m_ampl > 0);
  }
  
  void kill() {
    psg.setOff(m_chan);
    psg.setPercOff(m_chan);
    m_ampl = 0;
  }
};


const ushort MAX_VOICES = 9;

static Voice voices[MAX_VOICES];

// MIDI synthesiser ---------------------------------------

// Deals with assigning note on/note off to voices

static const uint8_t PERC_CHANNEL = 9;

static const note_t
  PERC_MIN = 35,
  PERC_MAX = 59;
  
static const struct FXParams perc_params[PERC_MAX-PERC_MIN+1] PROGMEM = {
  // Mappings are from the General MIDI spec at https://www.midi.org/specifications-old/item/gm-level-1-sound-set
  
  // Params are: noisefreq, tonefreq, envdecay, freqdecay, timer, shape
  //
  // noisefreq: AY noise period. 0 = brightest hiss, 15 = darkest.
  //            16 or higher means "no noise on this voice".
  // tonefreq:  tone divisor, f = 1000000 / (16 * divisor). 0 = no tone.
  //            BIGGER divisor = LOWER pitch.
  // envdecay:  AY envelope period. Bigger = slower envelope = longer sound.
  // freqdecay: added to tonefreq each 10ms tick, so pitch falls over time.
  // timer:     amplitude decay rate; length in ms is about 10230 / timer.
  // shape:     AY envelope shape. 9 = single decay, the usual drum shape.
  
  { 9, 900, 800, 40, 50, 9 },   // 35 Acoustic bass drum
  { 16, 2000, 1500, 16, 15, 9 },  // 36 (C) 808 Bass Drum 1
  { 5, 0, 300, 0, 80, 9 },      // 37 Side Stick
  { 6, 0, 1200, 0, 30, 9  },    // 38 Acoustic snare
  
  { 16, 75, 150, 0, 60, 9 },     // 39 (D#) Clave  [GM calls 39 Hand Clap]
  { 6, 400, 1200, 11, 30, 9  }, // 40 Electric snare
  { 16, 893, 800, 20, 30, 9 },  // 41 Low floor tom   ~70Hz  (was 700)
  { 0, 0, 300, 0, 80, 9 },      // 42 Closed Hi Hat
  
  { 16, 735, 800, 13, 30, 9 },   // 43 (G) High Floor Tom ~85Hz (was 400)
  { 0, 0, 600, 0, 50, 9 },      // 44 Pedal Hi-Hat
  { 16, 625, 1400, 30, 25, 9 }, // 45 Low Tom         ~100Hz (was 800)
  { 0, 0, 800, 0, 40, 9 },      // 46 Open Hi-Hat
  
  { 16, 521, 1400, 20, 25, 9 }, // 47 (B) Low-Mid Tom ~120Hz (was 600)
  { 16, 431, 1500, 15, 22, 9 }, // 48 Hi-Mid Tom      ~145Hz (was 450)
  { 1, 0, 2500, 0, 8, 9 },      // 49 Crash Cymbal 1  (was tonal "Effect #1":
                                //    { 16, 320, 1500, 20, 22, 9 })
  { 16, 357, 1500, 10, 22, 9 }, // 50 High Tom        ~175Hz (was 300)

  { 2, 0, 1700, 0, 14, 9 },     // 51 Ride Cymbal 1
  { 0, 0, 2200, 0, 9, 9 },      // 52 Chinese Cymbal
  { 5, 71, 900, 0, 26, 9 },     // 53 Ride Bell   ~880Hz ping over noise
  { 1, 0, 420, 0, 45, 9 },      // 54 Tambourine

  { 0, 0, 1100, 0, 20, 9 },     // 55 Splash Cymbal
  { 16, 78, 600, 0, 32, 9 },    // 56 Cowbell     ~800Hz, no noise
  { 2, 0, 2300, 0, 9, 9 },      // 57 Crash Cymbal 2
  { 6, 0, 950, 0, 22, 9 },      // 58 Vibraslap

  { 3, 0, 1500, 0, 16, 9 },     // 59 Ride Cymbal 2
};
  
  

static const int REQ_MAP_SIZE = (N_NOTES+7) / 8;
static uint8_t m_requestMap[REQ_MAP_SIZE];
  // Bit is set for each note being requested
static  midictrl_t m_velocity[N_NOTES];
  // Requested velocity for each note
static  midictrl_t m_chan[N_NOTES];
  // Requested MIDI channel for each note
static uint8_t m_highest, m_lowest;
  // Highest and lowest requested notes

static const uint8_t NO_NOTE = 0xFF;
static const uint8_t PERC_NOTE = 0xFE;
static uint8_t m_playing[MAX_VOICES];
  // Which note each voice is playing

static const uint8_t NO_VOICE = 0xFF;
static uint8_t m_voiceNo[N_NOTES];
  // Which voice is playing each note
  

static bool startNote(ushort idx) {
  for (ushort i = 0; i < MAX_VOICES; i++) {
    if (m_playing[i] == NO_NOTE) {
      voices[i].start(MIDI_MIN + idx, m_velocity[idx], m_chan[idx]);
      m_playing[i] = idx;
      m_voiceNo[idx] = i;
          //Serial.print("Voice #: ");
          //Serial.println(i);
      return true;
    }
  }
  return false;
}
  
// Applies the global Drums controls to one drum's parameters. Works on the
// RAM copy pulled out of PROGMEM, so the built-in kit table is untouched and
// the modifiers reshape every drum consistently.
static void applyDrumMods(FXParams &f) {
  uint8_t tune = params[P_DRUM_TUNE];              // 50..200 %
  uint8_t len  = params[P_DRUM_DECAY];             // 50..200 %
  uint8_t bend = params[P_DRUM_BEND];              // 0..200 %
  int8_t  nz   = (int8_t)params[P_DRUM_NOISE] - 7; // -7..+7

  // Pitch. tonefreq is a DIVISOR, so a higher tune % must make it smaller.
  // tonefreq 0 means "no tone" and has to stay 0.
  if (f.tonefreq > 0 && tune != 100) {
    uint32_t d = ((uint32_t)f.tonefreq * 100UL) / tune;
    if (d < 1) d = 1;
    if (d > 4095) d = 4095;
    f.tonefreq = (ushort)d;
  }

  // Length. The envelope period stretches, and the amplitude decay rate
  // shrinks (length is roughly 10230/timer ms), so both ends agree.
  if (len != 100) {
    uint32_t e = ((uint32_t)f.envdecay * len) / 100UL;
    if (e > 65535UL) e = 65535UL;
    f.envdecay = (ushort)e;
    uint32_t t = ((uint32_t)f.timer * 100UL) / len;
    if (t < 1) t = 1;
    f.timer = (ushort)t;
  }

  // Pitch-drop amount on kicks and toms.
  if (bend != 100) {
    f.freqdecay = (ushort)(((uint32_t)f.freqdecay * bend) / 100UL);
  }

  // Noise colour. Entries at 16 or above mean "no noise" to
  // setToneAndNoise(), so leave those alone or a shift would switch noise on.
  if (f.noisefreq < 16 && nz != 0) {
    int v = (int)f.noisefreq + nz;
    if (v < 0) v = 0;
    if (v > 15) v = 15;
    f.noisefreq = (ushort)v;
  }
}

static bool startPercussion(note_t note) {
  ushort i;
  for (i = 0; i < MAX_VOICES; i++) {
    //if (m_playing[i] == NO_NOTE || m_playing[i] == PERC_NOTE) {
    if (i != NO_VOICE && m_playing[i] == NO_NOTE) {
      if (note >= PERC_MIN && note <= PERC_MAX) {
        FXParams fxp;
        memcpy_P(&fxp, &perc_params[note-PERC_MIN], sizeof(FXParams));
        applyDrumMods(fxp);
        voices[i].startFX(fxp);
        m_playing[i] = PERC_NOTE;

      }
      return true;
    }        
//              Serial.print("m_playing: ");
//          Serial.println(m_playing[i]);
  }
  return false;
}
    
static bool stopNote(ushort idx) {
  uint8_t v = m_voiceNo[idx];
  if (v != NO_VOICE && m_playing[v] != NO_NOTE) {
    voices[v].stop();
    m_playing[v] = NO_NOTE;
    m_voiceNo[idx] = NO_VOICE;
    return true;
  }
  return false;
}

static void stopOneNote() {
  uint8_t v, chosen = NO_NOTE;

  // At this point we have run out of voices.
  // Pick a voice and stop it. We leave a voice alone
  // if it's playing the highest requested note. If it's
  // playing the lowest requested note we look for a 'better'
  // note, but stop it if none found.

  for (v = 0; v < MAX_VOICES; v++) {
    uint8_t idx = m_playing[v];
    if (idx == NO_NOTE) {// Uh? Perhaps called by mistake.
      return;
    }

    if (idx == m_highest) {
      continue;
    }

    if (idx == PERC_NOTE) {
      continue;
    }
      
    chosen = idx;
    if (idx != m_lowest) {
      break;
    }
    // else keep going, we may find a better one
  }

  if (chosen != NO_NOTE) {
    stopNote(chosen);
  }
}

static void updateRequestedNotes() {
  m_highest = m_lowest = NO_NOTE;
  ushort i,j;
    
  // Check highest requested note is playing
  // Return true if note was restarted; false if already playing 
  for (i = 0; i < REQ_MAP_SIZE; i++) {
    uint8_t req = m_requestMap[i];
    if (req == 0) {
      continue;
    }

    for (j = 0; j < 8; j++) {
      if (req & (1 << j)) {
        ushort idx = i*8 + j;
        if (m_lowest == NO_NOTE || m_lowest > idx) {
          m_lowest = idx;
        }
        if (m_highest==NO_NOTE || m_highest < idx)  {
          m_highest = idx;
        }
      }
    }
  }
}

static bool restartANote() {
  if (m_highest != NO_NOTE && m_voiceNo[m_highest] == NO_VOICE) {
    return startNote(m_highest);
  }

  if (m_lowest != NO_NOTE && m_voiceNo[m_lowest] == NO_VOICE) {
    return startNote(m_lowest);
  }

  return false;
}

static void synth_init () {
  ushort i;

  for (i = 0; i < REQ_MAP_SIZE; i++) {
    m_requestMap[i] = 0;
  }

  for (i = 0; i < N_NOTES; i++) {
    m_velocity[i] = 0;
    m_voiceNo[i] = NO_VOICE;
  }
    
  for (i = 0; i < MAX_VOICES; i++) {
    m_playing[i] = NO_NOTE;
  }
    
  m_highest = m_lowest = NO_NOTE;
}

static void noteOff(midictrl_t chan, note_t note, midictrl_t vel) {
  if (chan == PERC_CHANNEL || note < MIDI_MIN || note > MIDI_MAX) {
    return; // Just ignore it
  }

    if (note < MIDI_MIN || note > MIDI_MAX) {
    return; // Just ignore it
  }

  ushort idx = note - MIDI_MIN;

  m_requestMap[idx/8] &= ~(1 << (idx & 7));
  m_velocity[idx] = 0;
  updateRequestedNotes();
    
  if (stopNote(idx)) {
    restartANote();
  }
}

static void noteOn(midictrl_t chan, note_t note, midictrl_t vel) {
  if (vel == 0) {
    noteOff(chan, note, 0);
    return;
  }

  if (chan == PERC_CHANNEL) {
    //if (!startPercussion(note)) {
      stopOneNote();
      startPercussion(note);
    //}
    return;
  }
    
  // Regular note processing now
    
  if (note < MIDI_MIN || note > MIDI_MAX) {
    return; // Just ignore it
  }

  ushort idx = note - MIDI_MIN;
    
  if (m_voiceNo[idx] != NO_VOICE) {
    return; // Already playing. Ignore this request.
  }

  m_requestMap[idx/8] |= 1 << (idx & 7);
  m_velocity[idx] = vel;
  m_chan[idx] = chan;
  updateRequestedNotes();
    
  if (!startNote(idx)) {
     stopOneNote();
     startNote(idx);
  }
}
  
  
// --- Effects engine + serial parameter protocol --------------------------
//
// Everything here is driven by the params[] bank (see parameters.h, which
// generate.py produces alongside the web panel). The panel talks over the
// Leonardo's USB-CDC serial port -- a separate USB interface from USB-MIDI
// and from Serial1's DIN MIDI, so all three coexist.
//
// Protocol (ASCII, one command per line):
//   P:<idx>:<value>    set one parameter     -> V:<idx>:<clamped value>
//   DUMP               request all values    -> PRESET:v0,v1,...
//   LOAD:v0,v1,...     apply a full preset   -> PRESET:v0,v1,...
//   SAVE               persist to EEPROM     -> SAVED:1
//   DEFAULTS           restore defaults      -> PRESET:v0,v1,...
// Unrecognised lines (e.g. #ifdef DEBUG logging sharing the port) are
// ignored; the panel only acts on PRESET:/V:/SAVED: replies.

static uint8_t  vibPhase = 0;       // 0..255, wraps
static uint16_t vibPhaseStep = 13;
static uint8_t  tremPhase = 0;
static uint16_t tremPhaseStep = 10;

// 32-point sine table, one full cycle, range approx -127..127.
// Shared by the vibrato and tremolo LFOs.
static const int8_t lfoSine[32] PROGMEM = {
    0,  25,  49,  71,  90, 106, 117, 125,
  127, 125, 117, 106,  90,  71,  49,  25,
    0, -25, -49, -71, -90,-106,-117,-125,
 -127,-125,-117,-106, -90, -71, -49, -25
};

static void recalcLfoSteps() {
  // Tick rate is ~100Hz: phase steps (256 per cycle) needed per tick
  // = rateHz * 256 / 100 = rateX10 * 256 / 1000.
  vibPhaseStep = (uint16_t)(((uint32_t)params[P_VIB_RATE] * 256UL) / 1000UL);
  if (vibPhaseStep == 0) vibPhaseStep = 1;
  tremPhaseStep = (uint16_t)(((uint32_t)params[P_TREM_RATE] * 256UL) / 1000UL);
  if (tremPhaseStep == 0) tremPhaseStep = 1;
}

// Tracks which chip/sub-channel currently has the envelope-mode bit set,
// so it can be cleared cleanly when the buzz target moves elsewhere.
static int8_t g_buzzChip = -1, g_buzzSub = -1;

static void applyBuzzyBass() {
  int8_t targetVoice = -1;

  if (params[P_BUZZ_ENABLE] && m_lowest != NO_NOTE) {
    uint8_t v = m_voiceNo[m_lowest];
    if (v != NO_VOICE && m_playing[v] != PERC_NOTE && voices[v].isPlaying()) {
      targetVoice = v;
    }
  }

  int8_t newChip = -1, newSub = -1;
  if (targetVoice >= 0) {
    newChip = targetVoice % 3;
    newSub  = targetVoice / 3;
  }

  if ((newChip != g_buzzChip || newSub != g_buzzSub) && g_buzzChip >= 0) {
    psg.clearBuzz(g_buzzChip, g_buzzSub);
  }

  if (newChip >= 0) {
    psg.applyBuzz(newChip, newSub, voices[targetVoice].m_pitch,
                  params[P_BUZZ_RATIO],
                  pgm_read_byte(&buzzShapes[params[P_BUZZ_SHAPE] & 3]));
  }

  g_buzzChip = newChip;
  g_buzzSub  = newSub;
}

static void sendPreset() {
  Serial.print(F("PRESET:"));
  for (uint8_t i = 0; i < NUM_PARAMS; i++) {
    Serial.print(params[i]);
    if (i < NUM_PARAMS - 1) Serial.print(',');
  }
  Serial.println();
}

static void handleCommand(char *cmd) {
  if (strncmp(cmd, "P:", 2) == 0) {
    char *sep = strchr(cmd + 2, ':');
    if (!sep) return;
    uint8_t idx = (uint8_t)atoi(cmd + 2);
    if (idx >= NUM_PARAMS) return;
    setParam(idx, atoi(sep + 1));
    recalcLfoSteps();
    Serial.print(F("V:"));
    Serial.print(idx);
    Serial.print(':');
    Serial.println(params[idx]);
  }
  else if (strcmp(cmd, "DUMP") == 0) {
    sendPreset();
  }
  else if (strncmp(cmd, "LOAD:", 5) == 0) {
    char *p = cmd + 5;
    uint8_t i = 0;
    while (*p && i < NUM_PARAMS) {
      setParam(i++, atoi(p));
      p = strchr(p, ',');
      if (!p) break;
      p++;
    }
    recalcLfoSteps();
    sendPreset();
  }
  else if (strcmp(cmd, "SAVE") == 0) {
    saveParamsToEEPROM();
    Serial.println(F("SAVED:1"));
  }
  else if (strcmp(cmd, "DEFAULTS") == 0) {
    loadDefaults();
    recalcLfoSteps();
    sendPreset();
  }
  // anything else: ignore silently
}

// Big enough for "LOAD:" + NUM_PARAMS 3-digit values with commas.
static char    cmdBuf[96];
static uint8_t cmdLen = 0;

static void pollSerialControl() {
  while (Serial.available()) {
    char c = Serial.read();
    if (c == '\n' || c == '\r') {
      if (cmdLen > 0) {
        cmdBuf[cmdLen] = '\0';
        handleCommand(cmdBuf);
        cmdLen = 0;
      }
    }
    else if (cmdLen < sizeof(cmdBuf) - 1) {
      cmdBuf[cmdLen++] = c;
    }
  }
}

static void update100Hz() {
  // Advance the LFOs once per tick (shared across voices).
  int8_t vibSample = 0;
  if (params[P_VIB_ENABLE]) {
    vibPhase += vibPhaseStep;
    vibSample = (int8_t)pgm_read_byte(&lfoSine[vibPhase >> 3]);
  }
  uint8_t tremCut = 0;
  if (params[P_TREM_ENABLE]) {
    tremPhase += tremPhaseStep;
    int s = (int8_t)pgm_read_byte(&lfoSine[tremPhase >> 3]);
    tremCut = (uint8_t)(((s + 127) * params[P_TREM_DEPTH]) >> 8); // 0..depth
  }

  for (ushort i = 0; i < MAX_VOICES; i++) {
    voices[i].update100Hz();

    if (m_playing[i] == PERC_NOTE && ! (voices[i].isPlaying())) {
      m_playing[i] = NO_NOTE;
      restartANote();
    }

    // Final tone/amplitude write for sounding melodic voices, with all
    // modifiers applied. voices[i].update100Hz() already wrote its plain
    // value into the register cache; writing again just replaces it in RAM
    // before the hardware flush, and setTone() is idempotent on the mixer
    // bits, so this layering is safe.
    if (m_playing[i] != PERC_NOTE && voices[i].isPlaying()) {
      ushort p = voices[i].m_pitch;

      // Vibrato with delayed onset: waits P_VIB_DELAY ticks (10ms each)
      // after note start, then fades the depth in over ~250ms.
      if (params[P_VIB_ENABLE] && params[P_VIB_DEPTH] > 0) {
        uint16_t delayTicks = params[P_VIB_DELAY];
        if (voices[i].m_age > delayTicks) {
          uint16_t ramp = voices[i].m_age - delayTicks;
          uint8_t depth = params[P_VIB_DEPTH];
          if (ramp < 25) depth = (uint8_t)(((uint16_t)depth * ramp) / 25);
          int32_t off = ((int32_t)p * vibSample * depth) >> 14;
          int32_t wp = (int32_t)p + off;
          if (wp < 1) wp = 1;
          if (wp > 4095) wp = 4095;
          p = (ushort)wp;
        }
      }

      int a = (voices[i].m_ampl >> 6) - tremCut;
      if (a < 0) a = 0;

      // Noise blend: mixes the AY noise generator into the voice. NOTE:
      // the noise period register is per-chip and shared with percussion
      // -- a drum and a noise-blended voice on the same chip fight over
      // it, last writer wins. Chip-level quirk, documented behaviour.
      if (params[P_NOISE_ENABLE]) {
        psg.setToneAndNoise(i, p, params[P_NOISE_PERIOD], a);
      } else {
        psg.setTone(i, p, a);
      }
    }
  }

  applyBuzzyBass();
}

// Main code ----------------------------------------------

static unsigned long lastUpdate = 0;

void setup() {
  // Hold in reset while we set up the reset
  pinMode(nRESET, OUTPUT);
  digitalWrite(nRESET, LOW);

  pinMode(clkOUT, OUTPUT);
  digitalWrite(clkOUT, LOW);
  clockSetup();

  pinMode(BC2_A, OUTPUT);
  digitalWrite(BC2_A, LOW); // BC2 low
  pinMode(BDIR_A, OUTPUT);
  digitalWrite(BDIR_A, LOW); // BDIR low

  pinMode(BC2_B, OUTPUT);
  digitalWrite(BC2_B, LOW); // BC2 low
  pinMode(BDIR_B, OUTPUT);
  digitalWrite(BDIR_B, LOW); // BDIR low

  pinMode(BC2_C, OUTPUT);
  digitalWrite(BC2_C, LOW); // BC2 low
  pinMode(BDIR_C, OUTPUT);
  digitalWrite(BDIR_C, LOW); // BDIR low

  for (ushort i = 0; i < 8; i++) {
    uint8_t pin = pgm_read_byte(&dbus[i]);
    pinMode(pin, OUTPUT);
    digitalWrite(pin, LOW); // Set bus low
  }

  // Resolve dbus/BDIR/BC2 pins to their AVR port registers + bitmasks now
  // that they're all configured as OUTPUT. Must happen before any
  // writeReg()/setData() call (i.e. before psg.init() below).
  initBusPins();

  delay(100);
  digitalWrite(nRESET, HIGH); // Release Reset
  delay(10);

  lastUpdate = millis();
  
  psg.init();
  for (ushort i = 0; i < MAX_VOICES; i++) {
    voices[i].init(i);
  }
  synth_init();

  // Parameter bank: restore the last EEPROM-saved bank if it matches the
  // current generated layout, otherwise start from the generated defaults.
  if (!loadParamsFromEEPROM()) {
    loadDefaults();
  }
  recalcLfoSteps();

  // Serial (USB-CDC) is needed unconditionally for the parameter protocol,
  // not just for #ifdef DEBUG logging.
  Serial.begin(115200);
  sendPreset(); // let an already-connected panel resync after a board reset

#ifdef SERIALMIDI
  // Initiate MIDI communications, listen to all channels
  MIDI.begin(MIDI_CHANNEL_OMNI);
#endif
}

void handleMidiMessage(midiEventPacket_t &rx) {
  if (rx.header==0x9) {// Note on
    noteOn(rx.byte1 & 0xF, rx.byte2, rx.byte3);
  }
  else if (rx.header==0x8) {// Note off
    noteOff(rx.byte1 & 0xF, rx.byte2, rx.byte3);
  }
  else if (rx.header==0xB) {// Control Change
    if (rx.byte2 == 0x78 || rx.byte2 == 0x79 || rx.byte2 == 0x7B) {// AllSoundOff, ResetAllControllers, or AllNotesOff
      // Kill Voices
      //for (ushort i = 0; i < MAX_VOICES; i++) {
        //voices[i].kill();
        //delay(1);
        //psg.init();
        //delay(1);
        resetFunc();
      //}
    }
  }
}

void loop() {
  midiEventPacket_t rx;

  pollSerialControl(); // BUZZ/VIB parameter commands over USB-CDC serial

#ifdef USBMIDI
  rx = MidiUSB.read();

#ifdef DEBUG
  //MIDI debugging
  if (rx.header != 0) {
    Serial.print("Received USB: ");
    Serial.print(rx.header, HEX);
    Serial.print("-");
    Serial.print(rx.byte1, HEX);
    Serial.print("-");
    Serial.print(rx.byte2, HEX);
    Serial.print("-");
    Serial.println(rx.byte3, HEX);
  }
#endif

  handleMidiMessage(rx);
#endif

#ifdef SERIALMIDI
  //Check for serial MIDI messages
  //MIDI.read();
  while (MIDI.read()) {
    // Create midiEventPacket_t
    rx = 
      {
        byte(MIDI.getType() >>4), 
        byte(MIDI.getType() | ((MIDI.getChannel()-1) & 0x0f)), /* getChannel() returns values from 1 to 16 */
        MIDI.getData1(), 
        MIDI.getData2()
      };

#ifdef DEBUG
    //MIDI debugging
    if (rx.header != 0) {
      Serial.print("Received MIDI: ");
      Serial.print(rx.header, HEX);
      Serial.print("-");
      Serial.print(rx.byte1, HEX);
      Serial.print("-");
      Serial.print(rx.byte2, HEX);
      Serial.print("-");
      Serial.println(rx.byte3, HEX);
    }
#endif

    handleMidiMessage(rx);
  }
#endif

  unsigned long now = millis();
  if ((now - lastUpdate) >= 10) {
    update100Hz();
    lastUpdate += 10; // was += 5 against a >10ms check, causing the
                       // envelope/perc update rate to drift ~2x fast
                       // whenever the loop fell behind and had to catch up
  }
  
  psg.updateAll();

}
