// AUTO-GENERATED by generate.py -- do not edit by hand.
// Edit PARAMS in generate.py and re-run it instead.
#ifndef PARAMETERS_H
#define PARAMETERS_H

#include <avr/pgmspace.h>

#define NUM_PARAMS 44
#define PARAM_LAYOUT_VERSION 0x45

enum {
  P_BUZZ_ENABLE = 0,  // Buzzy Bass: Enable [0..1] default 0
  P_BUZZ_RATIO = 1,  // Buzzy Bass: Ratio [1..8] default 1
  P_BUZZ_SHAPE = 2,  // Buzzy Bass: Shape [0..3] default 0
  P_BUZZ_DETUNE = 3,  // Buzzy Bass: Detune [0..64] default 32
  P_WARP_MODE = 4,  // Warp Zone: Mode [0..10] default 0
  P_WARP_RATE = 5,  // Warp Zone: Rate [1..120] default 30
  P_WARP_DEPTH = 6,  // Warp Zone: Depth [1..63] default 20
  P_WARP_MOTION = 7,  // Warp Zone: Motion [0..64] default 0
  P_UNI_ENABLE = 8,  // Unison: Enable [0..1] default 0
  P_UNI_DETUNE = 9,  // Unison: Detune [1..32] default 8
  P_VIB_ENABLE = 10,  // Vibrato: Enable [0..1] default 0
  P_VIB_RATE = 11,  // Vibrato: Rate [1..200] default 50
  P_VIB_DEPTH = 12,  // Vibrato: Depth [0..31] default 6
  P_VIB_DELAY = 13,  // Vibrato: Delay [0..200] default 0
  P_TREM_ENABLE = 14,  // Tremolo: Enable [0..1] default 0
  P_TREM_RATE = 15,  // Tremolo: Rate [1..200] default 40
  P_TREM_DEPTH = 16,  // Tremolo: Depth [0..15] default 5
  P_NOISE_ENABLE = 17,  // Noise Blend: Enable [0..1] default 0
  P_NOISE_PERIOD = 18,  // Noise Blend: Period [0..15] default 8
  P_DRUM_TUNE = 19,  // Drums: Tune [50..200] default 100
  P_DRUM_DECAY = 20,  // Drums: Decay [50..200] default 100
  P_DRUM_BEND = 21,  // Drums: Bend [0..200] default 100
  P_DRUM_NOISE = 22,  // Drums: Noise [0..14] default 7
  P_DRUM_ROLL = 23,  // Drum FX: Roll [0..50] default 0
  P_DRUM_FLAM = 24,  // Drum FX: Flam [0..30] default 0
  P_DRUM_REVERSE = 25,  // Drum FX: Reverse [0..1] default 0
  P_DRUM_CHAOS = 26,  // Drum FX: Chaos [0..63] default 0
  P_ARP_MODE = 27,  // Auto FX: Arp [0..6] default 0
  P_ARP_RATE = 28,  // Auto FX: Arp Rate [1..50] default 17
  P_SWEEP_AMOUNT = 29,  // Auto FX: Sweep [0..64] default 32
  P_RETRIG_RATE = 30,  // Auto FX: Retrigger [0..50] default 0
  P_ENV_MODE = 31,  // Envelope: Mode [0..1] default 0
  P_ENV_ATTACK = 32,  // Envelope: Attack [1..32] default 1
  P_ENV_DECAY = 33,  // Envelope: Decay [1..32] default 26
  P_ENV_SUSTAIN = 34,  // Envelope: Sustain [0..32] default 32
  P_ENV_RELEASE = 35,  // Envelope: Release [1..32] default 19
  P_GLIDE = 36,  // Pitch & Response: Glide [0..100] default 0
  P_TRANSPOSE = 37,  // Pitch & Response: Transpose [0..48] default 24
  P_MIX_NOISE = 38,  // Mixer: Noise [0..15] default 15
  P_MIX_TONE = 39,  // Mixer: Tone [0..15] default 15
  P_MIX_DRUM = 40,  // Mixer: Drums [0..15] default 15
  P_TEMPERAMENT = 41,  // Tuning: Temperament [0..9] default 0
  P_TEMPER_ROOT = 42,  // Tuning: Root [0..11] default 0
  P_VEL_SENSE = 43,  // Pitch & Response: Velocity [0..1] default 1
};

static const uint8_t PARAM_MIN[NUM_PARAMS] PROGMEM = { 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 50, 50, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 };
static const uint8_t PARAM_MAX[NUM_PARAMS] PROGMEM = { 1, 8, 3, 64, 10, 120, 63, 64, 1, 32, 1, 200, 31, 200, 1, 200, 15, 1, 15, 200, 200, 200, 14, 50, 30, 1, 63, 6, 50, 64, 50, 1, 32, 32, 32, 32, 100, 48, 15, 15, 15, 9, 11, 1 };
static const uint8_t PARAM_DEFAULT[NUM_PARAMS] PROGMEM = { 0, 1, 0, 32, 0, 30, 20, 0, 0, 8, 0, 50, 6, 0, 0, 40, 5, 0, 8, 100, 100, 100, 7, 0, 0, 0, 0, 0, 17, 32, 0, 0, 1, 26, 32, 19, 0, 24, 15, 15, 15, 0, 0, 1 };

// Ticks between events for the re-strike controls (Drum Roll,
// Retrigger), indexed by the parameter value. The tick is 100Hz, so
// ticks = 100 / rate. Rate is spaced EXPONENTIALLY rather than
// linearly: rhythm is heard in ratios, so a linear Hz control puts a
// doubling between the first two positions and nothing at all across
// the top half. This curve runs 1.5Hz to 45Hz at about 6% per step.
static const uint8_t RATE_EVERY[51] PROGMEM = {
  0, 67, 62, 58, 54, 51, 47, 44, 41, 38, 36, 33, 31, 29, 27, 25, 24,
  22, 20, 19, 18, 17, 16, 14, 14, 13, 12, 11, 10, 10, 9, 8, 8, 7,
  7, 6, 6, 5, 5, 5, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2,
};

// Tone-period multiplier for the Warp pitch modes, x256, indexed by
// warp depth. Pitch is heard in semitones, so the table is
// exponential: a linear multiplier put half the total drop in the
// first quarter of the fader. This spreads 30 semitones evenly.
static const uint16_t WARP_STRETCH[64] PROGMEM = {
  256, 263, 270, 278, 286, 294, 302, 310, 319, 328, 337, 346,
  356, 366, 376, 387, 398, 409, 420, 432, 444, 456, 469, 482,
  495, 509, 523, 538, 553, 568, 584, 601, 617, 635, 652, 670,
  689, 708, 728, 748, 769, 791, 813, 835, 859, 883, 907, 933,
  959, 985, 1013, 1041, 1070, 1100, 1131, 1162, 1195, 1228, 1262, 1297,
  1333, 1371, 1409, 1448,
};

// Envelope segment rates, in 1/16ths of an amplitude unit per 100Hz
// tick, indexed by the parameter value. The parameter is a TIME and
// the scale is exponential, 10ms to 4s: as a linear per-tick rate it
// was reciprocal, so 1->2 halved the time while 31->32 moved it 4ms.
// A 1/16th accumulator keeps the slow end usable, which an integer
// rate could not -- 1023/400 rounds to 3 and swallows the top third
// of the fader.
static const uint16_t ENV_RATE[33] PROGMEM = {
  0, 16368, 13491, 11120, 9166, 7555, 6227, 5133, 4231, 3487, 2874,
  2369, 1953, 1610, 1327, 1094, 901, 743, 612, 505, 416, 343,
  283, 233, 192, 158, 130, 108, 89, 73, 60, 50, 41,
};

// Master mixer attenuation, in amplitude-register steps, indexed by
// the mixer setting. Applied by SUBTRACTION, which is a true dB cut
// and treats a quiet note the same as a loud one -- multiplying the
// register instead truncated a decaying note to silence several fader
// positions before a full one. The curve is an audio taper: the top
// half covers about 13dB and it accelerates below that, because the
// AY's own steps grow from roughly 1.5dB at the top to 3.5dB at the
// bottom and a straight mapping therefore dives.
static const uint8_t MIX_ATTEN[16] PROGMEM = {
  15, 13, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 2, 1, 1, 0
};

#endif // PARAMETERS_H
