// AUTO-GENERATED by generate.py -- do not edit by hand.
// Edit PARAMS in generate.py and re-run it instead.
#ifndef PARAMETERS_H
#define PARAMETERS_H

#include <avr/pgmspace.h>

#define NUM_PARAMS 32
#define PARAM_LAYOUT_VERSION 0x6F

enum {
  P_BUZZ_ENABLE = 0,  // Buzzy Bass: Enable [0..1] default 0
  P_BUZZ_RATIO = 1,  // Buzzy Bass: Ratio [1..8] default 1
  P_BUZZ_SHAPE = 2,  // Buzzy Bass: Shape [0..3] default 0
  P_BUZZ_DETUNE = 3,  // Buzzy Bass: Detune [0..64] default 32
  P_WARP_MODE = 4,  // Warp Zone: Mode [0..4] default 0
  P_WARP_RATE = 5,  // Warp Zone: Rate [1..120] default 30
  P_WARP_DEPTH = 6,  // Warp Zone: Depth [1..63] default 20
  P_VIB_ENABLE = 7,  // Vibrato: Enable [0..1] default 0
  P_VIB_RATE = 8,  // Vibrato: Rate [1..200] default 50
  P_VIB_DEPTH = 9,  // Vibrato: Depth [0..31] default 6
  P_VIB_DELAY = 10,  // Vibrato: Delay [0..200] default 0
  P_TREM_ENABLE = 11,  // Tremolo: Enable [0..1] default 0
  P_TREM_RATE = 12,  // Tremolo: Rate [1..200] default 40
  P_TREM_DEPTH = 13,  // Tremolo: Depth [0..15] default 5
  P_NOISE_ENABLE = 14,  // Noise Blend: Enable [0..1] default 0
  P_NOISE_PERIOD = 15,  // Noise Blend: Period [0..15] default 8
  P_DRUM_TUNE = 16,  // Drums: Tune [50..200] default 100
  P_DRUM_DECAY = 17,  // Drums: Decay [50..200] default 100
  P_DRUM_BEND = 18,  // Drums: Bend [0..200] default 100
  P_DRUM_NOISE = 19,  // Drums: Noise [0..14] default 7
  P_ARP_MODE = 20,  // Auto FX: Arp [0..6] default 0
  P_ARP_RATE = 21,  // Auto FX: Arp Rate [1..50] default 17
  P_SWEEP_AMOUNT = 22,  // Auto FX: Sweep [0..64] default 32
  P_RETRIG_RATE = 23,  // Auto FX: Retrigger [0..50] default 0
  P_ENV_MODE = 24,  // Envelope: Mode [0..1] default 0
  P_ENV_ATTACK = 25,  // Envelope: Attack [1..32] default 1
  P_ENV_DECAY = 26,  // Envelope: Decay [1..32] default 8
  P_ENV_SUSTAIN = 27,  // Envelope: Sustain [0..32] default 32
  P_ENV_RELEASE = 28,  // Envelope: Release [1..32] default 32
  P_GLIDE = 29,  // Pitch & Response: Glide [0..100] default 0
  P_TRANSPOSE = 30,  // Pitch & Response: Transpose [0..48] default 24
  P_VEL_SENSE = 31,  // Pitch & Response: Velocity [0..1] default 1
};

static const uint8_t PARAM_MIN[NUM_PARAMS] PROGMEM = { 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 50, 50, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0 };
static const uint8_t PARAM_MAX[NUM_PARAMS] PROGMEM = { 1, 8, 3, 64, 4, 120, 63, 1, 200, 31, 200, 1, 200, 15, 1, 15, 200, 200, 200, 14, 6, 50, 64, 50, 1, 32, 32, 32, 32, 100, 48, 1 };
static const uint8_t PARAM_DEFAULT[NUM_PARAMS] PROGMEM = { 0, 1, 0, 32, 0, 30, 20, 0, 50, 6, 0, 0, 40, 5, 0, 8, 100, 100, 100, 7, 0, 17, 32, 0, 0, 1, 8, 32, 32, 0, 24, 1 };

#endif // PARAMETERS_H
