// AUTO-GENERATED by generate.py -- do not edit by hand.
// Cent offsets are imported from temperaments.py, the same definitions
// used by the minichord firmware.
#ifndef TEMPERAMENTS_H
#define TEMPERAMENTS_H

#include <avr/pgmspace.h>

#define NUM_TEMPERAMENTS 10
#define TEMPER_CENT_SPAN 40   // table covers -SPAN..+SPAN cents

// Cents from equal temperament, pitch classes C..B. A is 0 in every row.
static const int8_t temperCents[NUM_TEMPERAMENTS][12] PROGMEM = {
  {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 },   // equal
  { 10, -14,   3,  21,  -3,  14, -10,   7, -17,   0,  17,  -7 },   // quarter-comma meantone
  { 16,  27,  20,  31,   2,  14,   6,  18,  29,   0,  12,   4 },   // five-limit just (C major)
  { -6,   8,  -2, -12,   2,  -8,   6,  -4,  10,   0, -10,   4 },   // pythagorean
  { 12,   2,   4,   6,   2,  10,   0,   8,   4,   0,   8,   4 },   // werckmeister III
  { 10,   0,   3,   4,  -3,   8,   0,   7,   2,   0,   6,  -1 },   // kirnberger III
  {  6,   0,   2,   4,  -2,   8,  -2,   4,   2,   0,   6,  -4 },   // vallotti
  {  6,  -4,   2,   0,  -2,   4,  -6,   4,  -2,   0,   2,  -4 },   // young no. 2
  {  8,  -2,   3,   2,  -3,   6,  -4,   5,   0,   0,   4,  -1 },   // kellner
  {  5,  -7,   2,  10,  -2,   7,  -5,   3,  -8,   0,   8,  -3 },   // sixth-comma meantone
};

// 32768 * 2^(-cents/1200), indexed by cents + TEMPER_CENT_SPAN.
// A tone period is a DIVISOR, so a sharper note needs a SMALLER one.
static const uint16_t temperFactor[81] PROGMEM = {
  33534, 33515, 33495, 33476, 33457, 33437, 33418, 33399, 33379, 33360,
  33341, 33322, 33302, 33283, 33264, 33245, 33225, 33206, 33187, 33168,
  33149, 33130, 33110, 33091, 33072, 33053, 33034, 33015, 32996, 32977,
  32958, 32939, 32920, 32901, 32882, 32863, 32844, 32825, 32806, 32787,
  32768, 32749, 32730, 32711, 32692, 32673, 32655, 32636, 32617, 32598,
  32579, 32560, 32542, 32523, 32504, 32485, 32467, 32448, 32429, 32410,
  32392, 32373, 32354, 32336, 32317, 32298, 32280, 32261, 32242, 32224,
  32205, 32186, 32168, 32149, 32131, 32112, 32094, 32075, 32057, 32038,
  32020,
};

#endif // TEMPERAMENTS_H
